# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'home.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class UI_homeWidget(object):
    def setupUi(self, mainWidget):
        #定义图标
        loginIcon = QtGui.QIcon()
        loginIcon.addPixmap(QtGui.QPixmap("icon/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.helpIcon = QtGui.QPixmap("icon/help.png")
        QtWidgets.QToolTip.setFont(QtGui.QFont('SansSerif', 10))
        #定义窗口
        mainWidget.setObjectName("mainWidget")
        mainWidget.resize(500, 640)
        mainWidget.setWindowIcon(loginIcon)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(mainWidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        #定义按钮横向布局
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(mainWidget)
        self.tabWidget.setObjectName("tabWidget")
        #垂直布局
        self.verticalLayout.addWidget(self.tabWidget)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        #Next&finish按钮
        self.confirmBtn = QtWidgets.QPushButton(mainWidget)
        self.confirmBtn.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.confirmBtn)
        #取消按钮
        self.cancelBtn = QtWidgets.QPushButton(mainWidget)
        self.cancelBtn.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.cancelBtn)
        self.horizontalLayout.setStretch(0, 4)
        self.horizontalLayout.setStretch(1, 1)
        self.horizontalLayout.setStretch(2, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout)

        # Step1的控件
        self.firstStepControl(self.tabWidget)
        # Step2的控件
        self.secondStepControl(self.tabWidget)
        # Step3的控件
        self.thirdStepControl(self.tabWidget)
        # Step4的控件
        self.fourthStepControl(self.tabWidget)
        # Step5的控件
        self.fifthStepControl(self.tabWidget)
        #空间文字描述
        self.retranslateUi(mainWidget)

        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(mainWidget)

        #初始化控件信号槽
        self.connectSignal(mainWidget)



    def retranslateUi(self, mainWidget):
        _translate = QtCore.QCoreApplication.translate
        mainWidget.setWindowTitle(_translate("mainWidget", "追溯分析系统部署工具"))
        self.group_1.setTitle(_translate("mainWidget", "业务库"))
        self.label_72.setText(_translate("mainWidget", "端口"))
        self.label_73.setText(_translate("mainWidget", "密码"))
        self.lineEdit_1.setText(_translate("mainWidget", "192.168.227.139"))
        self.label_76.setText(_translate("mainWidget", "账号"))
        self.label_77.setText(_translate("mainWidget", "数据库"))
        self.label_78.setText(_translate("mainWidget", "地址"))
        self.lineEdit_2.setText(_translate("mainWidget", "1433"))
        self.lineEdit_5.setItemText(0, _translate("mainWidget", "请选择业务库"))
        self.group_2.setTitle(_translate("mainWidget", "历史库"))
        self.label_85.setText(_translate("mainWidget", "数据库"))
        self.lineEdit_7.setText(_translate("mainWidget", "192.168.227.139"))
        self.label_81.setText(_translate("mainWidget", "密码"))
        self.label_86.setText(_translate("mainWidget", "地址"))
        self.lineEdit_8.setText(_translate("mainWidget", "1433"))
        self.label_84.setText(_translate("mainWidget", "账号"))
        self.label_80.setText(_translate("mainWidget", "端口"))
        self.lineEdit_6.setText(_translate("mainWidget", "是否抽取历史库"))
        self.lineEdit_11.setItemText(0, _translate("mainWidget", "请选择历史库"))
        self.group_3.setTitle(_translate("mainWidget", "系统库"))
        self.label_64.setText(_translate("mainWidget", "端口"))
        self.label_65.setText(_translate("mainWidget", "密码"))
        self.lineEdit_12.setText(_translate("mainWidget", "192.168.227.139"))
        self.label_68.setText(_translate("mainWidget", "账号"))
        self.label_69.setText(_translate("mainWidget", "数据库"))
        self.label_70.setText(_translate("mainWidget", "地址"))
        self.lineEdit_13.setText(_translate("mainWidget", "1433"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabStep_1), _translate("mainWidget", "Step1.数据库"))
        self.group_4.setTitle(_translate("mainWidget", "BI库"))
        self.lineEdit_18.setText(_translate("mainWidget", "1433"))
        self.label_41.setText(_translate("mainWidget", "密码"))
        self.label_35.setText(_translate("mainWidget", "端口"))
        self.lineEdit_17.setText(_translate("mainWidget", "192.168.227.139"))
        self.label_43.setText(_translate("mainWidget", "账号"))
        self.label_44.setText(_translate("mainWidget", "数据库"))
        self.label_45.setText(_translate("mainWidget", "地址"))
        self.label_20.setText(_translate("mainWidget", "数据源编号"))
        self.label_21.setText(_translate("mainWidget", "数据源名称"))
        self.group_5.setTitle(_translate("mainWidget", "工艺参数库"))
        self.label_55.setText(_translate("mainWidget", "文件路径"))
        self.label_51.setText(_translate("mainWidget", "账号"))
        self.label_48.setText(_translate("mainWidget", "密码"))
        self.label_47.setText(_translate("mainWidget", "端口"))
        self.label_53.setText(_translate("mainWidget", "地址"))
        self.lineEdit_25.setText(_translate("mainWidget", "1433"))
        self.label_52.setText(_translate("mainWidget", "数据库"))
        self.lineEdit_24.setText(_translate("mainWidget", "192.168.227.139"))
        self.label_56.setText(_translate("mainWidget", "开始年月"))
        self.label_57.setText(_translate("mainWidget", "初始值(MB)"))
        self.label_58.setText(_translate("mainWidget", "结束年月"))
        self.label_59.setText(_translate("mainWidget", "增长值(MB)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabStep_2), _translate("mainWidget", "Step2.数据仓库"))
        self.group_6.setTitle(_translate("mainWidget", "基础配置"))
        self.label_15.setText(_translate("mainWidget", "系统版本"))
        self.label_18.setText(_translate("mainWidget", "业务端服务地址"))
        self.label_16.setText(_translate("mainWidget", "业务端服务端口"))
        self.group_7.setTitle(_translate("mainWidget", "部署程序"))
        self.label_3.setText(_translate("mainWidget", "网络共享地址"))
        self.label_5.setText(_translate("mainWidget", "共享密码"))
        self.label_4.setText(_translate("mainWidget", "共享账号"))
        self.group8.setTitle(_translate("mainWidget", "部署地址"))
        self.label_9.setText(_translate("mainWidget", "拷贝目录"))
        self.label_10.setText(_translate("mainWidget", "PowerShell目录"))
        self.label_12.setText(_translate("mainWidget", "安装目录"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabStep_3), _translate("mainWidget", "Step3.部署配置"))
        self.group_9.setTitle(_translate("mainWidget", "基础配置"))
        self.label_95.setText(_translate("mainWidget", "服务端口"))
        self.group_10.setTitle(_translate("mainWidget", "工艺参数"))
        self.label_89.setText(_translate("mainWidget", "密码"))
        self.label_27.setText(_translate("mainWidget", "账号"))
        self.label_25.setText(_translate("mainWidget", "映射目录"))
        self.label_24.setText(_translate("mainWidget", "映射地址"))
        self.checkBox_2.setText(_translate("mainWidget", "是否启用工艺参数网络映射"))
        self.group_11.setTitle(_translate("mainWidget", "单点登录"))
        self.label_32.setText(_translate("mainWidget", "接口端口"))
        self.label_31.setText(_translate("mainWidget", "页面端口"))
        self.label_29.setText(_translate("mainWidget", "服务地址(MI)"))
        self.lineEdit_48.setText(_translate("mainWidget", "是否启用单点登录"))
        self.group_12.setTitle(_translate("mainWidget", "ETL配置"))
        self.label_93.setText(_translate("mainWidget", "账号"))
        self.label_37.setText(_translate("mainWidget", "ETL端口"))
        self.label_39.setText(_translate("mainWidget", "JVM(MB)"))
        self.label_92.setText(_translate("mainWidget", "抽取抽取频率(分钟)"))
        self.label_94.setText(_translate("mainWidget", "密码"))
        self.label_30.setText(_translate("mainWidget", "工艺参数抽取目录"))
        self.checkBox_4.setText(_translate("mainWidget", "是否启用登录"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabStep_4), _translate("mainWidget", "Step4.系统配置"))
        self.group_13.setTitle(_translate("mainWidget", "定制配置"))
        self.lineEdit_64.setItemText(0, _translate("mainWidget", "停用"))
        self.lineEdit_64.setItemText(1, _translate("mainWidget", "启用"))
        self.lineEdit_65.setItemText(0, _translate("mainWidget", "停用"))
        self.lineEdit_65.setItemText(1, _translate("mainWidget", "启用"))
        self.lineEdit_60.setItemText(0, _translate("mainWidget", "停用"))
        self.lineEdit_60.setItemText(1, _translate("mainWidget", "启用"))
        self.lineEdit_59.setItemText(0, _translate("mainWidget", "停用"))
        self.lineEdit_59.setItemText(1, _translate("mainWidget", "启用"))
        self.label_104.setText(_translate("mainWidget", "断链"))
        self.lineEdit_61.setItemText(0, _translate("mainWidget", "停用"))
        self.lineEdit_61.setItemText(1, _translate("mainWidget", "启用"))
        self.lineEdit_63.setItemText(0, _translate("mainWidget", "停用"))
        self.lineEdit_63.setItemText(1, _translate("mainWidget", "启用"))
        self.lineEdit_62.setItemText(0, _translate("mainWidget", "停用"))
        self.lineEdit_62.setItemText(1, _translate("mainWidget", "启用"))
        self.label_105.setText(_translate("mainWidget", "过滤万能工单"))
        self.label_97.setText(_translate("mainWidget", "重构版本"))
        self.label_102.setText(_translate("mainWidget", "FGB"))
        self.label_99.setText(_translate("mainWidget", "设备维护"))
        self.label_100.setText(_translate("mainWidget", "工具管理"))
        self.label_98.setText(_translate("mainWidget", "遏制"))
        self.label_103.setText(_translate("mainWidget", "视频监控"))
        self.label_101.setText(_translate("mainWidget", "工艺参数"))
        self.lineEdit_58.setItemText(0, _translate("mainWidget", "重构后"))
        self.lineEdit_58.setItemText(1, _translate("mainWidget", "重构前"))
        self.lineEdit_66.setItemText(0, _translate("mainWidget", "过滤"))
        self.lineEdit_66.setItemText(1, _translate("mainWidget", "不过滤"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabStep_5), _translate("mainWidget", "Step5.工厂定制"))
        self.confirmBtn.setText(_translate("mainWidget", "Next"))
        self.cancelBtn.setText(_translate("mainWidget", "Cancel"))


    def firstStepControl(self, tabObj):

        self.tabStep_1 = QtWidgets.QWidget()
        self.tabStep_1.setObjectName("tabStep_1")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tabStep_1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")

        self.group_1 = QtWidgets.QGroupBox(self.tabStep_1)
        self.group_1.setObjectName("group_1")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.group_1)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setContentsMargins(10, -1, 10, -1)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_72 = QtWidgets.QLabel(self.group_1)
        self.label_72.setAlignment(QtCore.Qt.AlignCenter)
        self.label_72.setObjectName("label_72")
        self.gridLayout_8.addWidget(self.label_72, 0, 2, 1, 1)
        self.label_73 = QtWidgets.QLabel(self.group_1)
        self.label_73.setAlignment(QtCore.Qt.AlignCenter)
        self.label_73.setObjectName("label_73")
        self.gridLayout_8.addWidget(self.label_73, 1, 2, 1, 1)
        self.lineEdit_1 = QtWidgets.QLineEdit(self.group_1)
        self.lineEdit_1.setObjectName("lineEdit_1")
        self.gridLayout_8.addWidget(self.lineEdit_1, 0, 1, 1, 1)
        self.label_74 = QtWidgets.QLabel(self.group_1)
        self.label_74.setMaximumSize(QtCore.QSize(20, 20))
        self.label_74.setText("")
        self.label_74.setPixmap(self.helpIcon)
        self.label_74.setScaledContents(True)
        self.label_74.setObjectName("label_74")
        self.gridLayout_8.addWidget(self.label_74, 1, 4, 1, 1)
        self.label_75 = QtWidgets.QLabel(self.group_1)
        self.label_75.setMaximumSize(QtCore.QSize(20, 20))
        self.label_75.setText("")
        self.label_75.setPixmap(self.helpIcon)
        self.label_75.setScaledContents(True)
        self.label_75.setObjectName("label_75")
        self.gridLayout_8.addWidget(self.label_75, 2, 4, 1, 1)
        self.label_76 = QtWidgets.QLabel(self.group_1)
        self.label_76.setAlignment(QtCore.Qt.AlignCenter)
        self.label_76.setObjectName("label_76")
        self.gridLayout_8.addWidget(self.label_76, 1, 0, 1, 1)
        self.label_77 = QtWidgets.QLabel(self.group_1)
        self.label_77.setAlignment(QtCore.Qt.AlignCenter)
        self.label_77.setObjectName("label_77")
        self.gridLayout_8.addWidget(self.label_77, 2, 0, 1, 1)
        self.label_78 = QtWidgets.QLabel(self.group_1)
        self.label_78.setAlignment(QtCore.Qt.AlignCenter)
        self.label_78.setObjectName("label_78")
        self.gridLayout_8.addWidget(self.label_78, 0, 0, 1, 1)
        self.label_79 = QtWidgets.QLabel(self.group_1)
        self.label_79.setMaximumSize(QtCore.QSize(20, 20))
        self.label_79.setText("")
        self.label_79.setPixmap(self.helpIcon)
        self.label_79.setScaledContents(True)
        self.label_79.setObjectName("label_79")
        self.label_79.setToolTip('<b>业务数据库</b>的IP地址和端口号，端口默认1433')
        self.gridLayout_8.addWidget(self.label_79, 0, 4, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.group_1)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_8.addWidget(self.lineEdit_2, 0, 3, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.group_1)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout_8.addWidget(self.lineEdit_3, 1, 1, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.group_1)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout_8.addWidget(self.lineEdit_4, 1, 3, 1, 1)
        self.lineEdit_5 = QtWidgets.QComboBox(self.group_1)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_5.addItem("")
        self.gridLayout_8.addWidget(self.lineEdit_5, 2, 1, 1, 3)
        self.gridLayout_8.setColumnStretch(1, 3)
        self.gridLayout_8.setColumnStretch(2, 1)
        self.gridLayout_8.setColumnStretch(3, 3)
        self.horizontalLayout_8.addLayout(self.gridLayout_8)
        self.verticalLayout_3.addWidget(self.group_1)

        self.group_2 = QtWidgets.QGroupBox(self.tabStep_1)
        self.group_2.setObjectName("group_2")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.group_2)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setContentsMargins(10, -1, 10, -1)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_85 = QtWidgets.QLabel(self.group_2)
        self.label_85.setAlignment(QtCore.Qt.AlignCenter)
        self.label_85.setObjectName("label_85")
        self.gridLayout_9.addWidget(self.label_85, 3, 0, 1, 1)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.group_2)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.gridLayout_9.addWidget(self.lineEdit_7, 1, 1, 1, 1)
        self.label_81 = QtWidgets.QLabel(self.group_2)
        self.label_81.setAlignment(QtCore.Qt.AlignCenter)
        self.label_81.setObjectName("label_81")
        self.gridLayout_9.addWidget(self.label_81, 2, 2, 1, 1)

        self.lineEdit_8 = QtWidgets.QLineEdit(self.group_2)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.gridLayout_9.addWidget(self.lineEdit_8, 1, 3, 1, 1)

        self.label_86 = QtWidgets.QLabel(self.group_2)
        self.label_86.setAlignment(QtCore.Qt.AlignCenter)
        self.label_86.setObjectName("label_86")
        self.gridLayout_9.addWidget(self.label_86, 1, 0, 1, 1)
        self.label_83 = QtWidgets.QLabel(self.group_2)
        self.label_83.setMaximumSize(QtCore.QSize(20, 20))
        self.label_83.setText("")
        self.label_83.setPixmap(self.helpIcon)
        self.label_83.setScaledContents(True)
        self.label_83.setObjectName("label_83")
        self.gridLayout_9.addWidget(self.label_83, 3, 4, 1, 1)
        self.label_87 = QtWidgets.QLabel(self.group_2)
        self.label_87.setMaximumSize(QtCore.QSize(20, 20))
        self.label_87.setText("")
        self.label_87.setPixmap(self.helpIcon)
        self.label_87.setScaledContents(True)
        self.label_87.setObjectName("label_87")
        self.gridLayout_9.addWidget(self.label_87, 1, 4, 1, 1)

        self.lineEdit_9 = QtWidgets.QLineEdit(self.group_2)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.gridLayout_9.addWidget(self.lineEdit_9, 2, 1, 1, 1)

        self.lineEdit_10 = QtWidgets.QLineEdit(self.group_2)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.gridLayout_9.addWidget(self.lineEdit_10, 2, 3, 1, 1)
        self.label_82 = QtWidgets.QLabel(self.group_2)
        self.label_82.setMaximumSize(QtCore.QSize(20, 20))
        self.label_82.setText("")
        self.label_82.setPixmap(self.helpIcon)
        self.label_82.setScaledContents(True)
        self.label_82.setObjectName("label_82")
        self.gridLayout_9.addWidget(self.label_82, 2, 4, 1, 1)
        self.label_84 = QtWidgets.QLabel(self.group_2)
        self.label_84.setAlignment(QtCore.Qt.AlignCenter)
        self.label_84.setObjectName("label_84")
        self.gridLayout_9.addWidget(self.label_84, 2, 0, 1, 1)
        self.label_80 = QtWidgets.QLabel(self.group_2)
        self.label_80.setAlignment(QtCore.Qt.AlignCenter)
        self.label_80.setObjectName("label_80")
        self.gridLayout_9.addWidget(self.label_80, 1, 2, 1, 1)
        self.lineEdit_6 = QtWidgets.QCheckBox(self.group_2)
        self.lineEdit_6.setChecked(True)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.gridLayout_9.addWidget(self.lineEdit_6, 0, 0, 1, 4)
        self.label = QtWidgets.QLabel(self.group_2)
        self.label.setMaximumSize(QtCore.QSize(20, 20))
        self.label.setText("")
        self.label.setPixmap(self.helpIcon)
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.gridLayout_9.addWidget(self.label, 0, 4, 1, 1)
        self.lineEdit_11 = QtWidgets.QComboBox(self.group_2)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.lineEdit_11.addItem("")
        self.gridLayout_9.addWidget(self.lineEdit_11, 3, 1, 1, 3)
        self.gridLayout_9.setColumnStretch(1, 3)
        self.gridLayout_9.setColumnStretch(2, 1)
        self.gridLayout_9.setColumnStretch(3, 3)
        self.horizontalLayout_9.addLayout(self.gridLayout_9)
        self.verticalLayout_3.addWidget(self.group_2)

        self.group_3 = QtWidgets.QGroupBox(self.tabStep_1)
        self.group_3.setObjectName("group_3")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.group_3)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setContentsMargins(10, -1, 10, -1)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_64 = QtWidgets.QLabel(self.group_3)
        self.label_64.setAlignment(QtCore.Qt.AlignCenter)
        self.label_64.setObjectName("label_64")
        self.gridLayout_7.addWidget(self.label_64, 0, 2, 1, 1)
        self.label_65 = QtWidgets.QLabel(self.group_3)
        self.label_65.setAlignment(QtCore.Qt.AlignCenter)
        self.label_65.setObjectName("label_65")
        self.gridLayout_7.addWidget(self.label_65, 1, 2, 1, 1)
        self.lineEdit_12 = QtWidgets.QLineEdit(self.group_3)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.gridLayout_7.addWidget(self.lineEdit_12, 0, 1, 1, 1)
        self.label_66 = QtWidgets.QLabel(self.group_3)
        self.label_66.setMaximumSize(QtCore.QSize(20, 20))
        self.label_66.setText("")
        self.label_66.setPixmap(self.helpIcon)
        self.label_66.setScaledContents(True)
        self.label_66.setObjectName("label_66")
        self.gridLayout_7.addWidget(self.label_66, 1, 4, 1, 1)
        self.label_67 = QtWidgets.QLabel(self.group_3)
        self.label_67.setMaximumSize(QtCore.QSize(20, 20))
        self.label_67.setText("")
        self.label_67.setPixmap(self.helpIcon)
        self.label_67.setScaledContents(True)
        self.label_67.setObjectName("label_67")
        self.gridLayout_7.addWidget(self.label_67, 2, 4, 1, 1)
        self.label_68 = QtWidgets.QLabel(self.group_3)
        self.label_68.setAlignment(QtCore.Qt.AlignCenter)
        self.label_68.setObjectName("label_68")
        self.gridLayout_7.addWidget(self.label_68, 1, 0, 1, 1)
        self.label_69 = QtWidgets.QLabel(self.group_3)
        self.label_69.setAlignment(QtCore.Qt.AlignCenter)
        self.label_69.setObjectName("label_69")
        self.gridLayout_7.addWidget(self.label_69, 2, 0, 1, 1)
        self.label_70 = QtWidgets.QLabel(self.group_3)
        self.label_70.setAlignment(QtCore.Qt.AlignCenter)
        self.label_70.setObjectName("label_70")
        self.gridLayout_7.addWidget(self.label_70, 0, 0, 1, 1)
        self.label_71 = QtWidgets.QLabel(self.group_3)
        self.label_71.setMaximumSize(QtCore.QSize(20, 20))
        self.label_71.setText("")
        self.label_71.setPixmap(self.helpIcon)
        self.label_71.setScaledContents(True)
        self.label_71.setObjectName("label_71")
        self.gridLayout_7.addWidget(self.label_71, 0, 4, 1, 1)
        self.lineEdit_13 = QtWidgets.QLineEdit(self.group_3)
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.gridLayout_7.addWidget(self.lineEdit_13, 0, 3, 1, 1)
        self.lineEdit_16 = QtWidgets.QLineEdit(self.group_3)
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.gridLayout_7.addWidget(self.lineEdit_16, 2, 1, 1, 3)
        self.lineEdit_14 = QtWidgets.QLineEdit(self.group_3)
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.gridLayout_7.addWidget(self.lineEdit_14, 1, 1, 1, 1)
        self.lineEdit_15 = QtWidgets.QLineEdit(self.group_3)
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.gridLayout_7.addWidget(self.lineEdit_15, 1, 3, 1, 1)
        self.gridLayout_7.setColumnStretch(1, 3)
        self.gridLayout_7.setColumnStretch(2, 1)
        self.gridLayout_7.setColumnStretch(3, 3)
        self.horizontalLayout_7.addLayout(self.gridLayout_7)
        self.verticalLayout_3.addWidget(self.group_3)
        tabObj.addTab(self.tabStep_1, "")

        # Step2的控件
    def secondStepControl(self, tabObj):
        self.tabStep_2 = QtWidgets.QWidget()
        self.tabStep_2.setObjectName("tabStep_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tabStep_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.group_4 = QtWidgets.QGroupBox(self.tabStep_2)
        self.group_4.setObjectName("group_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.group_4)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setContentsMargins(10, -1, 10, -1)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_46 = QtWidgets.QLabel(self.group_4)
        self.label_46.setMaximumSize(QtCore.QSize(20, 20))
        self.label_46.setText("")
        self.label_46.setPixmap(self.helpIcon)
        self.label_46.setScaledContents(True)
        self.label_46.setObjectName("label_46")
        self.gridLayout_5.addWidget(self.label_46, 0, 4, 1, 1)
        self.lineEdit_18 = QtWidgets.QLineEdit(self.group_4)
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.gridLayout_5.addWidget(self.lineEdit_18, 0, 3, 1, 1)
        self.label_41 = QtWidgets.QLabel(self.group_4)
        self.label_41.setAlignment(QtCore.Qt.AlignCenter)
        self.label_41.setObjectName("label_41")
        self.gridLayout_5.addWidget(self.label_41, 1, 2, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.group_4)
        self.label_35.setAlignment(QtCore.Qt.AlignCenter)
        self.label_35.setObjectName("label_35")
        self.gridLayout_5.addWidget(self.label_35, 0, 2, 1, 1)
        self.label_38 = QtWidgets.QLabel(self.group_4)
        self.label_38.setMaximumSize(QtCore.QSize(20, 20))
        self.label_38.setText("")
        self.label_38.setPixmap(self.helpIcon)
        self.label_38.setScaledContents(True)
        self.label_38.setObjectName("label_38")
        self.gridLayout_5.addWidget(self.label_38, 1, 4, 1, 1)
        self.label_42 = QtWidgets.QLabel(self.group_4)
        self.label_42.setMaximumSize(QtCore.QSize(20, 20))
        self.label_42.setText("")
        self.label_42.setPixmap(self.helpIcon)
        self.label_42.setScaledContents(True)
        self.label_42.setObjectName("label_42")
        self.gridLayout_5.addWidget(self.label_42, 2, 4, 1, 1)
        self.lineEdit_17 = QtWidgets.QLineEdit(self.group_4)
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.gridLayout_5.addWidget(self.lineEdit_17, 0, 1, 1, 1)
        self.label_43 = QtWidgets.QLabel(self.group_4)
        self.label_43.setAlignment(QtCore.Qt.AlignCenter)
        self.label_43.setObjectName("label_43")
        self.gridLayout_5.addWidget(self.label_43, 1, 0, 1, 1)
        self.label_44 = QtWidgets.QLabel(self.group_4)
        self.label_44.setAlignment(QtCore.Qt.AlignCenter)
        self.label_44.setObjectName("label_44")
        self.gridLayout_5.addWidget(self.label_44, 2, 0, 1, 1)
        self.label_45 = QtWidgets.QLabel(self.group_4)
        self.label_45.setAlignment(QtCore.Qt.AlignCenter)
        self.label_45.setObjectName("label_45")
        self.gridLayout_5.addWidget(self.label_45, 0, 0, 1, 1)
        self.lineEdit_21 = QtWidgets.QLineEdit(self.group_4)
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.gridLayout_5.addWidget(self.lineEdit_21, 2, 1, 1, 3)
        self.lineEdit_19 = QtWidgets.QLineEdit(self.group_4)
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.gridLayout_5.addWidget(self.lineEdit_19, 1, 1, 1, 1)
        self.lineEdit_20 = QtWidgets.QLineEdit(self.group_4)
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.gridLayout_5.addWidget(self.lineEdit_20, 1, 3, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.group_4)
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.gridLayout_5.addWidget(self.label_20, 3, 0, 1, 1)
        self.lineEdit_22 = QtWidgets.QLineEdit(self.group_4)
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.gridLayout_5.addWidget(self.lineEdit_22, 3, 1, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.group_4)
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.gridLayout_5.addWidget(self.label_21, 3, 2, 1, 1)
        self.lineEdit_23 = QtWidgets.QLineEdit(self.group_4)
        self.lineEdit_23.setObjectName("lineEdit_23")
        self.gridLayout_5.addWidget(self.lineEdit_23, 3, 3, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.group_4)
        self.label_22.setMaximumSize(QtCore.QSize(20, 20))
        self.label_22.setText("")
        self.label_22.setPixmap(self.helpIcon)
        self.label_22.setScaledContents(True)
        self.label_22.setObjectName("label_22")
        self.gridLayout_5.addWidget(self.label_22, 3, 4, 1, 1)
        self.gridLayout_5.setColumnStretch(1, 3)
        self.gridLayout_5.setColumnStretch(2, 1)
        self.gridLayout_5.setColumnStretch(3, 3)
        self.horizontalLayout_5.addLayout(self.gridLayout_5)
        self.verticalLayout_4.addWidget(self.group_4)
        self.group_5 = QtWidgets.QGroupBox(self.tabStep_2)
        self.group_5.setObjectName("group_5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.group_5)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setContentsMargins(10, -1, 10, -1)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.lineEdit_29 = QtWidgets.QLineEdit(self.group_5)
        self.lineEdit_29.setObjectName("lineEdit_29")
        self.gridLayout_6.addWidget(self.lineEdit_29, 3, 1, 1, 3)
        self.label_55 = QtWidgets.QLabel(self.group_5)
        self.label_55.setAlignment(QtCore.Qt.AlignCenter)
        self.label_55.setObjectName("label_55")
        self.gridLayout_6.addWidget(self.label_55, 3, 0, 1, 1)
        self.label_51 = QtWidgets.QLabel(self.group_5)
        self.label_51.setAlignment(QtCore.Qt.AlignCenter)
        self.label_51.setObjectName("label_51")
        self.gridLayout_6.addWidget(self.label_51, 1, 0, 1, 1)
        self.label_48 = QtWidgets.QLabel(self.group_5)
        self.label_48.setAlignment(QtCore.Qt.AlignCenter)
        self.label_48.setObjectName("label_48")
        self.gridLayout_6.addWidget(self.label_48, 1, 2, 1, 1)
        self.label_47 = QtWidgets.QLabel(self.group_5)
        self.label_47.setAlignment(QtCore.Qt.AlignCenter)
        self.label_47.setObjectName("label_47")
        self.gridLayout_6.addWidget(self.label_47, 0, 2, 1, 1)
        self.label_53 = QtWidgets.QLabel(self.group_5)
        self.label_53.setAlignment(QtCore.Qt.AlignCenter)
        self.label_53.setObjectName("label_53")
        self.gridLayout_6.addWidget(self.label_53, 0, 0, 1, 1)
        self.label_54 = QtWidgets.QLabel(self.group_5)
        self.label_54.setMaximumSize(QtCore.QSize(20, 20))
        self.label_54.setText("")
        self.label_54.setPixmap(self.helpIcon)
        self.label_54.setScaledContents(True)
        self.label_54.setObjectName("label_54")
        self.gridLayout_6.addWidget(self.label_54, 0, 4, 1, 1)
        self.lineEdit_25 = QtWidgets.QLineEdit(self.group_5)
        self.lineEdit_25.setObjectName("lineEdit_25")
        self.gridLayout_6.addWidget(self.lineEdit_25, 0, 3, 1, 1)
        self.label_52 = QtWidgets.QLabel(self.group_5)
        self.label_52.setAlignment(QtCore.Qt.AlignCenter)
        self.label_52.setObjectName("label_52")
        self.gridLayout_6.addWidget(self.label_52, 2, 0, 1, 1)
        self.lineEdit_26 = QtWidgets.QLineEdit(self.group_5)
        self.lineEdit_26.setObjectName("lineEdit_26")
        self.gridLayout_6.addWidget(self.lineEdit_26, 1, 1, 1, 1)
        self.lineEdit_27 = QtWidgets.QLineEdit(self.group_5)
        self.lineEdit_27.setObjectName("lineEdit_27")
        self.gridLayout_6.addWidget(self.lineEdit_27, 1, 3, 1, 1)
        self.label_49 = QtWidgets.QLabel(self.group_5)
        self.label_49.setMaximumSize(QtCore.QSize(20, 20))
        self.label_49.setText("")
        self.label_49.setPixmap(self.helpIcon)
        self.label_49.setScaledContents(True)
        self.label_49.setObjectName("label_49")
        self.gridLayout_6.addWidget(self.label_49, 1, 4, 1, 1)
        self.lineEdit_24 = QtWidgets.QLineEdit(self.group_5)
        self.lineEdit_24.setObjectName("lineEdit_24")
        self.gridLayout_6.addWidget(self.lineEdit_24, 0, 1, 1, 1)
        self.lineEdit_28 = QtWidgets.QLineEdit(self.group_5)
        self.lineEdit_28.setObjectName("lineEdit_28")
        self.gridLayout_6.addWidget(self.lineEdit_28, 2, 1, 1, 3)
        self.label_50 = QtWidgets.QLabel(self.group_5)
        self.label_50.setMaximumSize(QtCore.QSize(20, 20))
        self.label_50.setText("")
        self.label_50.setPixmap(self.helpIcon)
        self.label_50.setScaledContents(True)
        self.label_50.setObjectName("label_50")
        self.gridLayout_6.addWidget(self.label_50, 2, 4, 1, 1)
        self.label_56 = QtWidgets.QLabel(self.group_5)
        self.label_56.setAlignment(QtCore.Qt.AlignCenter)
        self.label_56.setObjectName("label_56")
        self.gridLayout_6.addWidget(self.label_56, 4, 0, 1, 1)
        self.label_57 = QtWidgets.QLabel(self.group_5)
        self.label_57.setAlignment(QtCore.Qt.AlignCenter)
        self.label_57.setObjectName("label_57")
        self.gridLayout_6.addWidget(self.label_57, 5, 0, 1, 1)
        self.lineEdit_30 = QtWidgets.QLineEdit(self.group_5)
        self.lineEdit_30.setObjectName("lineEdit_30")
        self.gridLayout_6.addWidget(self.lineEdit_30, 4, 1, 1, 1)
        self.lineEdit_31 = QtWidgets.QLineEdit(self.group_5)
        self.lineEdit_31.setObjectName("lineEdit_31")
        self.gridLayout_6.addWidget(self.lineEdit_31, 4, 3, 1, 1)
        self.lineEdit_32 = QtWidgets.QLineEdit(self.group_5)
        self.lineEdit_32.setObjectName("lineEdit_32")
        self.gridLayout_6.addWidget(self.lineEdit_32, 5, 1, 1, 1)
        self.lineEdit_33 = QtWidgets.QLineEdit(self.group_5)
        self.lineEdit_33.setObjectName("lineEdit_33")
        self.gridLayout_6.addWidget(self.lineEdit_33, 5, 3, 1, 1)
        self.label_58 = QtWidgets.QLabel(self.group_5)
        self.label_58.setAlignment(QtCore.Qt.AlignCenter)
        self.label_58.setObjectName("label_58")
        self.gridLayout_6.addWidget(self.label_58, 4, 2, 1, 1)
        self.label_59 = QtWidgets.QLabel(self.group_5)
        self.label_59.setAlignment(QtCore.Qt.AlignCenter)
        self.label_59.setObjectName("label_59")
        self.gridLayout_6.addWidget(self.label_59, 5, 2, 1, 1)
        self.label_60 = QtWidgets.QLabel(self.group_5)
        self.label_60.setMaximumSize(QtCore.QSize(20, 20))
        self.label_60.setText("")
        self.label_60.setPixmap(self.helpIcon)
        self.label_60.setScaledContents(True)
        self.label_60.setObjectName("label_60")
        self.gridLayout_6.addWidget(self.label_60, 3, 4, 1, 1)
        self.label_61 = QtWidgets.QLabel(self.group_5)
        self.label_61.setMaximumSize(QtCore.QSize(20, 20))
        self.label_61.setText("")
        self.label_61.setPixmap(self.helpIcon)
        self.label_61.setScaledContents(True)
        self.label_61.setObjectName("label_61")
        self.gridLayout_6.addWidget(self.label_61, 4, 4, 1, 1)
        self.label_62 = QtWidgets.QLabel(self.group_5)
        self.label_62.setMaximumSize(QtCore.QSize(20, 20))
        self.label_62.setText("")
        self.label_62.setPixmap(self.helpIcon)
        self.label_62.setScaledContents(True)
        self.label_62.setObjectName("label_62")
        self.gridLayout_6.addWidget(self.label_62, 5, 4, 1, 1)
        self.gridLayout_6.setColumnStretch(1, 3)
        self.gridLayout_6.setColumnStretch(2, 1)
        self.gridLayout_6.setColumnStretch(3, 3)
        self.horizontalLayout_6.addLayout(self.gridLayout_6)
        self.verticalLayout_4.addWidget(self.group_5)
        self.verticalLayout_4.setStretch(0, 1)
        self.verticalLayout_4.setStretch(1, 2)
        tabObj.addTab(self.tabStep_2, "")

        # Step3的控件
    def thirdStepControl(self, tabObj):
        self.tabStep_3 = QtWidgets.QWidget()
        self.tabStep_3.setObjectName("tabStep_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tabStep_3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.group_6 = QtWidgets.QGroupBox(self.tabStep_3)
        self.group_6.setObjectName("group_6")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.group_6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setContentsMargins(10, -1, 10, -1)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_14 = QtWidgets.QLabel(self.group_6)
        self.label_14.setMaximumSize(QtCore.QSize(20, 20))
        self.label_14.setText("")
        self.label_14.setPixmap(self.helpIcon)
        self.label_14.setScaledContents(True)
        self.label_14.setObjectName("label_14")
        self.gridLayout_3.addWidget(self.label_14, 2, 2, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.group_6)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout_3.addWidget(self.label_15, 0, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.group_6)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.gridLayout_3.addWidget(self.label_18, 1, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.group_6)
        self.label_17.setMaximumSize(QtCore.QSize(20, 20))
        self.label_17.setText("")
        self.label_17.setPixmap(self.helpIcon)
        self.label_17.setScaledContents(True)
        self.label_17.setObjectName("label_17")
        self.gridLayout_3.addWidget(self.label_17, 1, 2, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.group_6)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout_3.addWidget(self.label_16, 2, 0, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.group_6)
        self.label_19.setMaximumSize(QtCore.QSize(20, 20))
        self.label_19.setText("")
        self.label_19.setPixmap(self.helpIcon)
        self.label_19.setScaledContents(True)
        self.label_19.setObjectName("label_19")
        self.gridLayout_3.addWidget(self.label_19, 0, 2, 1, 1)
        self.lineEdit_34 = QtWidgets.QLineEdit(self.group_6)
        self.lineEdit_34.setObjectName("lineEdit_34")
        self.gridLayout_3.addWidget(self.lineEdit_34, 0, 1, 1, 1)
        self.lineEdit_35 = QtWidgets.QLineEdit(self.group_6)
        self.lineEdit_35.setObjectName("lineEdit_35")
        self.gridLayout_3.addWidget(self.lineEdit_35, 1, 1, 1, 1)
        self.lineEdit_36 = QtWidgets.QLineEdit(self.group_6)
        self.lineEdit_36.setObjectName("lineEdit_36")
        self.gridLayout_3.addWidget(self.lineEdit_36, 2, 1, 1, 1)
        self.gridLayout_3.setColumnStretch(0, 1)
        self.gridLayout_3.setColumnStretch(1, 3)
        self.gridLayout_3.setColumnStretch(2, 1)
        self.horizontalLayout_4.addLayout(self.gridLayout_3)
        self.verticalLayout_5.addWidget(self.group_6)
        self.group_7 = QtWidgets.QGroupBox(self.tabStep_3)
        self.group_7.setObjectName("group_7")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.group_7)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(10, -1, 10, -1)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.group_7)
        self.label_2.setMaximumSize(QtCore.QSize(20, 20))
        self.label_2.setText("")
        self.label_2.setPixmap(self.helpIcon)
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.group_7)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.lineEdit_38 = QtWidgets.QLineEdit(self.group_7)
        self.lineEdit_38.setObjectName("lineEdit_38")
        self.gridLayout.addWidget(self.lineEdit_38, 1, 1, 1, 1)
        self.lineEdit_37 = QtWidgets.QLineEdit(self.group_7)
        self.lineEdit_37.setObjectName("lineEdit_37")
        self.gridLayout.addWidget(self.lineEdit_37, 0, 1, 1, 1)
        self.lineEdit_39 = QtWidgets.QLineEdit(self.group_7)
        self.lineEdit_39.setObjectName("lineEdit_39")
        self.gridLayout.addWidget(self.lineEdit_39, 2, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.group_7)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.group_7)
        self.label_7.setMaximumSize(QtCore.QSize(20, 20))
        self.label_7.setText("")
        self.label_7.setPixmap(self.helpIcon)
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 1, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.group_7)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.group_7)
        self.label_6.setMaximumSize(QtCore.QSize(20, 20))
        self.label_6.setText("")
        self.label_6.setPixmap(self.helpIcon)
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 2, 1, 1)
        self.gridLayout.setColumnStretch(0, 1)
        self.gridLayout.setColumnStretch(1, 3)
        self.gridLayout.setColumnStretch(2, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout)
        self.verticalLayout_5.addWidget(self.group_7)
        self.group8 = QtWidgets.QGroupBox(self.tabStep_3)
        self.group8.setObjectName("group8")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.group8)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setContentsMargins(10, -1, 10, -1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_8 = QtWidgets.QLabel(self.group8)
        self.label_8.setMaximumSize(QtCore.QSize(20, 20))
        self.label_8.setText("")
        self.label_8.setPixmap(self.helpIcon)
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 2, 2, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.group8)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 0, 0, 1, 1)
        self.lineEdit_41 = QtWidgets.QLineEdit(self.group8)
        self.lineEdit_41.setObjectName("lineEdit_41")
        self.gridLayout_2.addWidget(self.lineEdit_41, 1, 1, 1, 1)
        self.lineEdit_40 = QtWidgets.QLineEdit(self.group8)
        self.lineEdit_40.setObjectName("lineEdit_40")
        self.gridLayout_2.addWidget(self.lineEdit_40, 0, 1, 1, 1)
        self.lineEdit_42 = QtWidgets.QLineEdit(self.group8)
        self.lineEdit_42.setObjectName("lineEdit_42")
        self.gridLayout_2.addWidget(self.lineEdit_42, 2, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.group8)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 2, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.group8)
        self.label_11.setMaximumSize(QtCore.QSize(20, 20))
        self.label_11.setText("")
        self.label_11.setPixmap(self.helpIcon)
        self.label_11.setScaledContents(True)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 1, 2, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.group8)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 1, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.group8)
        self.label_13.setMaximumSize(QtCore.QSize(20, 20))
        self.label_13.setText("")
        self.label_13.setPixmap(self.helpIcon)
        self.label_13.setScaledContents(True)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 0, 2, 1, 1)
        self.gridLayout_2.setColumnStretch(0, 1)
        self.gridLayout_2.setColumnStretch(1, 3)
        self.gridLayout_2.setColumnStretch(2, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout_2)
        self.verticalLayout_5.addWidget(self.group8)
        tabObj.addTab(self.tabStep_3, "")

        # Step4的控件
    def fourthStepControl(self, tabObj):
        self.tabStep_4 = QtWidgets.QWidget()
        self.tabStep_4.setObjectName("tabStep_4")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.tabStep_4)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.group_9 = QtWidgets.QGroupBox(self.tabStep_4)
        self.group_9.setObjectName("group_9")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.group_9)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.gridLayout_12 = QtWidgets.QGridLayout()
        self.gridLayout_12.setContentsMargins(10, -1, 10, -1)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.label_95 = QtWidgets.QLabel(self.group_9)
        self.label_95.setAlignment(QtCore.Qt.AlignCenter)
        self.label_95.setObjectName("label_95")
        self.gridLayout_12.addWidget(self.label_95, 0, 0, 1, 1)
        self.lineEdit_43 = QtWidgets.QLineEdit(self.group_9)
        self.lineEdit_43.setObjectName("lineEdit_43")
        self.gridLayout_12.addWidget(self.lineEdit_43, 0, 1, 1, 1)
        self.label_96 = QtWidgets.QLabel(self.group_9)
        self.label_96.setMaximumSize(QtCore.QSize(20, 20))
        self.label_96.setText("")
        self.label_96.setPixmap(self.helpIcon)
        self.label_96.setScaledContents(True)
        self.label_96.setObjectName("label_96")
        self.gridLayout_12.addWidget(self.label_96, 0, 2, 1, 1)
        self.gridLayout_12.setColumnStretch(0, 1)
        self.gridLayout_12.setColumnStretch(1, 7)
        self.gridLayout_12.setColumnStretch(2, 1)
        self.verticalLayout_7.addLayout(self.gridLayout_12)
        self.verticalLayout_8.addWidget(self.group_9)
        self.group_10 = QtWidgets.QGroupBox(self.tabStep_4)
        self.group_10.setObjectName("group_10")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.group_10)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setContentsMargins(10, -1, 10, -1)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_89 = QtWidgets.QLabel(self.group_10)
        self.label_89.setAlignment(QtCore.Qt.AlignCenter)
        self.label_89.setObjectName("label_89")
        self.gridLayout_4.addWidget(self.label_89, 3, 2, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.group_10)
        self.label_26.setMaximumSize(QtCore.QSize(20, 20))
        self.label_26.setText("")
        self.label_26.setPixmap(self.helpIcon)
        self.label_26.setScaledContents(True)
        self.label_26.setObjectName("label_26")
        self.gridLayout_4.addWidget(self.label_26, 2, 4, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.group_10)
        self.label_27.setAlignment(QtCore.Qt.AlignCenter)
        self.label_27.setObjectName("label_27")
        self.gridLayout_4.addWidget(self.label_27, 3, 0, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.group_10)
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.gridLayout_4.addWidget(self.label_25, 2, 0, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.group_10)
        self.label_23.setMaximumSize(QtCore.QSize(20, 20))
        self.label_23.setText("")
        self.label_23.setPixmap(self.helpIcon)
        self.label_23.setScaledContents(True)
        self.label_23.setObjectName("label_23")
        self.gridLayout_4.addWidget(self.label_23, 3, 4, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.group_10)
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.gridLayout_4.addWidget(self.label_24, 1, 0, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.group_10)
        self.label_28.setMaximumSize(QtCore.QSize(20, 20))
        self.label_28.setText("")
        self.label_28.setPixmap(self.helpIcon)
        self.label_28.setScaledContents(True)
        self.label_28.setObjectName("label_28")
        self.gridLayout_4.addWidget(self.label_28, 1, 4, 1, 1)
        self.lineEdit_46 = QtWidgets.QLineEdit(self.group_10)
        self.lineEdit_46.setObjectName("lineEdit_46")
        self.gridLayout_4.addWidget(self.lineEdit_46, 3, 1, 1, 1)
        self.lineEdit_47 = QtWidgets.QLineEdit(self.group_10)
        self.lineEdit_47.setObjectName("lineEdit_47")
        self.gridLayout_4.addWidget(self.lineEdit_47, 3, 3, 1, 1)
        self.lineEdit_44 = QtWidgets.QLineEdit(self.group_10)
        self.lineEdit_44.setObjectName("lineEdit_44")
        self.gridLayout_4.addWidget(self.lineEdit_44, 1, 1, 1, 3)
        self.lineEdit_45 = QtWidgets.QLineEdit(self.group_10)
        self.lineEdit_45.setObjectName("lineEdit_45")
        self.gridLayout_4.addWidget(self.lineEdit_45, 2, 1, 1, 3)
        self.checkBox_2 = QtWidgets.QCheckBox(self.group_10)
        self.checkBox_2.setChecked(True)
        self.checkBox_2.setObjectName("checkBox_2")
        self.gridLayout_4.addWidget(self.checkBox_2, 0, 0, 1, 4)
        self.label_90 = QtWidgets.QLabel(self.group_10)
        self.label_90.setMaximumSize(QtCore.QSize(20, 20))
        self.label_90.setText("")
        self.label_90.setPixmap(self.helpIcon)
        self.label_90.setScaledContents(True)
        self.label_90.setObjectName("label_90")
        self.gridLayout_4.addWidget(self.label_90, 0, 4, 1, 1)
        self.gridLayout_4.setColumnStretch(0, 1)
        self.gridLayout_4.setColumnStretch(1, 3)
        self.gridLayout_4.setColumnStretch(2, 1)
        self.horizontalLayout_10.addLayout(self.gridLayout_4)
        self.verticalLayout_8.addWidget(self.group_10)
        self.group_11 = QtWidgets.QGroupBox(self.tabStep_4)
        self.group_11.setObjectName("group_11")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.group_11)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setContentsMargins(10, -1, 10, -1)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label_32 = QtWidgets.QLabel(self.group_11)
        self.label_32.setAlignment(QtCore.Qt.AlignCenter)
        self.label_32.setObjectName("label_32")
        self.gridLayout_10.addWidget(self.label_32, 2, 2, 1, 1)
        self.lineEdit_50 = QtWidgets.QLineEdit(self.group_11)
        self.lineEdit_50.setObjectName("lineEdit_50")
        self.gridLayout_10.addWidget(self.lineEdit_50, 2, 1, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.group_11)
        self.label_31.setAlignment(QtCore.Qt.AlignCenter)
        self.label_31.setObjectName("label_31")
        self.gridLayout_10.addWidget(self.label_31, 2, 0, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.group_11)
        self.label_29.setAlignment(QtCore.Qt.AlignCenter)
        self.label_29.setObjectName("label_29")
        self.gridLayout_10.addWidget(self.label_29, 1, 0, 1, 1)
        self.lineEdit_51 = QtWidgets.QLineEdit(self.group_11)
        self.lineEdit_51.setObjectName("lineEdit_51")
        self.gridLayout_10.addWidget(self.lineEdit_51, 2, 3, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.group_11)
        self.label_33.setMaximumSize(QtCore.QSize(20, 20))
        self.label_33.setText("")
        self.label_33.setPixmap(self.helpIcon)
        self.label_33.setScaledContents(True)
        self.label_33.setObjectName("label_33")
        self.gridLayout_10.addWidget(self.label_33, 2, 4, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.group_11)
        self.label_34.setMaximumSize(QtCore.QSize(20, 20))
        self.label_34.setText("")
        self.label_34.setPixmap(self.helpIcon)
        self.label_34.setScaledContents(True)
        self.label_34.setObjectName("label_34")
        self.gridLayout_10.addWidget(self.label_34, 1, 4, 1, 1)
        self.label_91 = QtWidgets.QLabel(self.group_11)
        self.label_91.setMaximumSize(QtCore.QSize(20, 20))
        self.label_91.setText("")
        self.label_91.setPixmap(self.helpIcon)
        self.label_91.setScaledContents(True)
        self.label_91.setObjectName("label_91")
        self.gridLayout_10.addWidget(self.label_91, 0, 4, 1, 1)
        self.lineEdit_48 = QtWidgets.QCheckBox(self.group_11)
        self.lineEdit_48.setChecked(True)
        self.lineEdit_48.setObjectName("lineEdit_48")
        self.gridLayout_10.addWidget(self.lineEdit_48, 0, 0, 1, 4)
        self.lineEdit_49 = QtWidgets.QLineEdit(self.group_11)
        self.lineEdit_49.setObjectName("lineEdit_49")
        self.gridLayout_10.addWidget(self.lineEdit_49, 1, 1, 1, 3)
        self.verticalLayout_6.addLayout(self.gridLayout_10)
        self.verticalLayout_8.addWidget(self.group_11)
        self.group_12 = QtWidgets.QGroupBox(self.tabStep_4)
        self.group_12.setObjectName("group_12")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.group_12)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.gridLayout_11 = QtWidgets.QGridLayout()
        self.gridLayout_11.setContentsMargins(10, -1, 10, -1)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.label_93 = QtWidgets.QLabel(self.group_12)
        self.label_93.setAlignment(QtCore.Qt.AlignCenter)
        self.label_93.setObjectName("label_93")
        self.gridLayout_11.addWidget(self.label_93, 3, 0, 1, 1)
        self.lineEdit_57 = QtWidgets.QLineEdit(self.group_12)
        self.lineEdit_57.setObjectName("lineEdit_57")
        self.gridLayout_11.addWidget(self.lineEdit_57, 3, 1, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.group_12)
        self.label_36.setMaximumSize(QtCore.QSize(20, 20))
        self.label_36.setText("")
        self.label_36.setPixmap(self.helpIcon)
        self.label_36.setScaledContents(True)
        self.label_36.setObjectName("label_36")
        self.gridLayout_11.addWidget(self.label_36, 2, 4, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.group_12)
        self.label_37.setAlignment(QtCore.Qt.AlignCenter)
        self.label_37.setObjectName("label_37")
        self.gridLayout_11.addWidget(self.label_37, 0, 0, 1, 1)
        self.label_39 = QtWidgets.QLabel(self.group_12)
        self.label_39.setAlignment(QtCore.Qt.AlignCenter)
        self.label_39.setObjectName("label_39")
        self.gridLayout_11.addWidget(self.label_39, 1, 0, 1, 1)
        self.label_88 = QtWidgets.QLabel(self.group_12)
        self.label_88.setMaximumSize(QtCore.QSize(20, 20))
        self.label_88.setText("")
        self.label_88.setPixmap(self.helpIcon)
        self.label_88.setScaledContents(True)
        self.label_88.setObjectName("label_88")
        self.gridLayout_11.addWidget(self.label_88, 0, 4, 1, 1)
        self.label_40 = QtWidgets.QLabel(self.group_12)
        self.label_40.setMaximumSize(QtCore.QSize(20, 20))
        self.label_40.setText("")
        self.label_40.setPixmap(self.helpIcon)
        self.label_40.setScaledContents(True)
        self.label_40.setObjectName("label_40")
        self.gridLayout_11.addWidget(self.label_40, 1, 4, 1, 1)
        self.lineEdit_55 = QtWidgets.QLineEdit(self.group_12)
        self.lineEdit_55.setObjectName("lineEdit_55")
        self.gridLayout_11.addWidget(self.lineEdit_55, 1, 1, 1, 1)
        self.lineEdit_53 = QtWidgets.QLineEdit(self.group_12)
        self.lineEdit_53.setObjectName("lineEdit_53")
        self.gridLayout_11.addWidget(self.lineEdit_53, 0, 1, 1, 1)
        self.label_92 = QtWidgets.QLabel(self.group_12)
        self.label_92.setAlignment(QtCore.Qt.AlignCenter)
        self.label_92.setObjectName("label_92")
        self.gridLayout_11.addWidget(self.label_92, 1, 2, 1, 1)
        self.label_94 = QtWidgets.QLabel(self.group_12)
        self.label_94.setAlignment(QtCore.Qt.AlignCenter)
        self.label_94.setObjectName("label_94")
        self.gridLayout_11.addWidget(self.label_94, 3, 2, 1, 1)
        self.lineEdit_52 = QtWidgets.QLineEdit(self.group_12)
        self.lineEdit_52.setObjectName("lineEdit_52")
        self.gridLayout_11.addWidget(self.lineEdit_52, 3, 3, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.group_12)
        self.label_30.setObjectName("label_30")
        self.gridLayout_11.addWidget(self.label_30, 0, 2, 1, 1)
        self.lineEdit_54 = QtWidgets.QLineEdit(self.group_12)
        self.lineEdit_54.setObjectName("lineEdit_54")
        self.gridLayout_11.addWidget(self.lineEdit_54, 0, 3, 1, 1)
        self.lineEdit_56 = QtWidgets.QLineEdit(self.group_12)
        self.lineEdit_56.setObjectName("lineEdit_56")
        self.gridLayout_11.addWidget(self.lineEdit_56, 1, 3, 1, 1)
        self.checkBox_4 = QtWidgets.QCheckBox(self.group_12)
        self.checkBox_4.setObjectName("checkBox_4")
        self.gridLayout_11.addWidget(self.checkBox_4, 2, 0, 1, 4)
        self.label_63 = QtWidgets.QLabel(self.group_12)
        self.label_63.setMaximumSize(QtCore.QSize(20, 20))
        self.label_63.setText("")
        self.label_63.setPixmap(self.helpIcon)
        self.label_63.setScaledContents(True)
        self.label_63.setObjectName("label_63")
        self.gridLayout_11.addWidget(self.label_63, 3, 4, 1, 1)
        self.gridLayout_11.setColumnStretch(0, 2)
        self.gridLayout_11.setColumnStretch(1, 4)
        self.gridLayout_11.setColumnStretch(2, 2)
        self.gridLayout_11.setColumnStretch(3, 4)
        self.horizontalLayout_12.addLayout(self.gridLayout_11)
        self.horizontalLayout_12.setStretch(0, 1)
        self.verticalLayout_8.addWidget(self.group_12)
        self.verticalLayout_8.setStretch(0, 1)
        self.verticalLayout_8.setStretch(1, 4)
        self.verticalLayout_8.setStretch(2, 3)
        self.verticalLayout_8.setStretch(3, 4)
        tabObj.addTab(self.tabStep_4, "")

        # Step5的控件
    def fifthStepControl(self, tabObj):
        self.tabStep_5 = QtWidgets.QWidget()
        self.tabStep_5.setObjectName("tabStep_5")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.tabStep_5)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.group_13 = QtWidgets.QGroupBox(self.tabStep_5)
        self.group_13.setObjectName("group_13")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.group_13)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.gridLayout_13 = QtWidgets.QGridLayout()
        self.gridLayout_13.setContentsMargins(10, 10, 50, 10)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.lineEdit_64 = QtWidgets.QComboBox(self.group_13)
        self.lineEdit_64.setObjectName("lineEdit_64")
        self.lineEdit_64.addItem("")
        self.lineEdit_64.addItem("")
        self.gridLayout_13.addWidget(self.lineEdit_64, 6, 1, 1, 1)
        self.lineEdit_65 = QtWidgets.QComboBox(self.group_13)
        self.lineEdit_65.setObjectName("lineEdit_65")
        self.lineEdit_65.addItem("")
        self.lineEdit_65.addItem("")
        self.gridLayout_13.addWidget(self.lineEdit_65, 7, 1, 1, 1)
        self.lineEdit_60 = QtWidgets.QComboBox(self.group_13)
        self.lineEdit_60.setObjectName("lineEdit_60")
        self.lineEdit_60.addItem("")
        self.lineEdit_60.addItem("")
        self.gridLayout_13.addWidget(self.lineEdit_60, 2, 1, 1, 1)
        self.lineEdit_59 = QtWidgets.QComboBox(self.group_13)
        self.lineEdit_59.setObjectName("lineEdit_59")
        self.lineEdit_59.addItem("")
        self.lineEdit_59.addItem("")
        self.gridLayout_13.addWidget(self.lineEdit_59, 1, 1, 1, 1)
        self.label_104 = QtWidgets.QLabel(self.group_13)
        self.label_104.setAlignment(QtCore.Qt.AlignCenter)
        self.label_104.setObjectName("label_104")
        self.gridLayout_13.addWidget(self.label_104, 7, 0, 1, 1)
        self.lineEdit_61 = QtWidgets.QComboBox(self.group_13)
        self.lineEdit_61.setObjectName("lineEdit_61")
        self.lineEdit_61.addItem("")
        self.lineEdit_61.addItem("")
        self.gridLayout_13.addWidget(self.lineEdit_61, 3, 1, 1, 1)
        self.lineEdit_63 = QtWidgets.QComboBox(self.group_13)
        self.lineEdit_63.setObjectName("lineEdit_63")
        self.lineEdit_63.addItem("")
        self.lineEdit_63.addItem("")
        self.gridLayout_13.addWidget(self.lineEdit_63, 5, 1, 1, 1)
        self.lineEdit_62 = QtWidgets.QComboBox(self.group_13)
        self.lineEdit_62.setObjectName("lineEdit_62")
        self.lineEdit_62.addItem("")
        self.lineEdit_62.addItem("")
        self.gridLayout_13.addWidget(self.lineEdit_62, 4, 1, 1, 1)
        self.label_105 = QtWidgets.QLabel(self.group_13)
        self.label_105.setAlignment(QtCore.Qt.AlignCenter)
        self.label_105.setObjectName("label_105")
        self.gridLayout_13.addWidget(self.label_105, 8, 0, 1, 1)
        self.label_97 = QtWidgets.QLabel(self.group_13)
        self.label_97.setAlignment(QtCore.Qt.AlignCenter)
        self.label_97.setObjectName("label_97")
        self.gridLayout_13.addWidget(self.label_97, 0, 0, 1, 1)
        self.label_102 = QtWidgets.QLabel(self.group_13)
        self.label_102.setAlignment(QtCore.Qt.AlignCenter)
        self.label_102.setObjectName("label_102")
        self.gridLayout_13.addWidget(self.label_102, 5, 0, 1, 1)
        self.label_99 = QtWidgets.QLabel(self.group_13)
        self.label_99.setAlignment(QtCore.Qt.AlignCenter)
        self.label_99.setObjectName("label_99")
        self.gridLayout_13.addWidget(self.label_99, 2, 0, 1, 1)
        self.label_100 = QtWidgets.QLabel(self.group_13)
        self.label_100.setAlignment(QtCore.Qt.AlignCenter)
        self.label_100.setObjectName("label_100")
        self.gridLayout_13.addWidget(self.label_100, 3, 0, 1, 1)
        self.label_98 = QtWidgets.QLabel(self.group_13)
        self.label_98.setAlignment(QtCore.Qt.AlignCenter)
        self.label_98.setObjectName("label_98")
        self.gridLayout_13.addWidget(self.label_98, 1, 0, 1, 1)
        self.label_103 = QtWidgets.QLabel(self.group_13)
        self.label_103.setAlignment(QtCore.Qt.AlignCenter)
        self.label_103.setObjectName("label_103")
        self.gridLayout_13.addWidget(self.label_103, 6, 0, 1, 1)
        self.label_101 = QtWidgets.QLabel(self.group_13)
        self.label_101.setAlignment(QtCore.Qt.AlignCenter)
        self.label_101.setObjectName("label_101")
        self.gridLayout_13.addWidget(self.label_101, 4, 0, 1, 1)
        self.lineEdit_58 = QtWidgets.QComboBox(self.group_13)
        self.lineEdit_58.setObjectName("lineEdit_58")
        self.lineEdit_58.addItem("")
        self.lineEdit_58.addItem("")
        self.gridLayout_13.addWidget(self.lineEdit_58, 0, 1, 1, 1)
        self.lineEdit_66 = QtWidgets.QComboBox(self.group_13)
        self.lineEdit_66.setObjectName("lineEdit_66")
        self.lineEdit_66.addItem("")
        self.lineEdit_66.addItem("")
        self.gridLayout_13.addWidget(self.lineEdit_66, 8, 1, 1, 1)
        self.label_106 = QtWidgets.QLabel(self.group_13)
        self.label_106.setMaximumSize(QtCore.QSize(20, 20))
        self.label_106.setText("")
        self.label_106.setPixmap(self.helpIcon)
        self.label_106.setScaledContents(True)
        self.label_106.setObjectName("label_106")
        self.gridLayout_13.addWidget(self.label_106, 0, 2, 1, 1)
        self.label_107 = QtWidgets.QLabel(self.group_13)
        self.label_107.setMaximumSize(QtCore.QSize(20, 20))
        self.label_107.setText("")
        self.label_107.setPixmap(self.helpIcon)
        self.label_107.setScaledContents(True)
        self.label_107.setObjectName("label_107")
        self.gridLayout_13.addWidget(self.label_107, 1, 2, 1, 1)
        self.label_108 = QtWidgets.QLabel(self.group_13)
        self.label_108.setMaximumSize(QtCore.QSize(20, 20))
        self.label_108.setText("")
        self.label_108.setPixmap(self.helpIcon)
        self.label_108.setScaledContents(True)
        self.label_108.setObjectName("label_108")
        self.gridLayout_13.addWidget(self.label_108, 2, 2, 1, 1)
        self.label_109 = QtWidgets.QLabel(self.group_13)
        self.label_109.setMaximumSize(QtCore.QSize(20, 20))
        self.label_109.setText("")
        self.label_109.setPixmap(self.helpIcon)
        self.label_109.setScaledContents(True)
        self.label_109.setObjectName("label_109")
        self.gridLayout_13.addWidget(self.label_109, 3, 2, 1, 1)
        self.label_110 = QtWidgets.QLabel(self.group_13)
        self.label_110.setMaximumSize(QtCore.QSize(20, 20))
        self.label_110.setText("")
        self.label_110.setPixmap(self.helpIcon)
        self.label_110.setScaledContents(True)
        self.label_110.setObjectName("label_110")
        self.gridLayout_13.addWidget(self.label_110, 4, 2, 1, 1)
        self.label_111 = QtWidgets.QLabel(self.group_13)
        self.label_111.setMaximumSize(QtCore.QSize(20, 20))
        self.label_111.setText("")
        self.label_111.setPixmap(self.helpIcon)
        self.label_111.setScaledContents(True)
        self.label_111.setObjectName("label_111")
        self.gridLayout_13.addWidget(self.label_111, 5, 2, 1, 1)
        self.label_112 = QtWidgets.QLabel(self.group_13)
        self.label_112.setMaximumSize(QtCore.QSize(20, 20))
        self.label_112.setText("")
        self.label_112.setPixmap(self.helpIcon)
        self.label_112.setScaledContents(True)
        self.label_112.setObjectName("label_112")
        self.gridLayout_13.addWidget(self.label_112, 6, 2, 1, 1)
        self.label_113 = QtWidgets.QLabel(self.group_13)
        self.label_113.setMaximumSize(QtCore.QSize(20, 20))
        self.label_113.setText("")
        self.label_113.setPixmap(self.helpIcon)
        self.label_113.setScaledContents(True)
        self.label_113.setObjectName("label_113")
        self.gridLayout_13.addWidget(self.label_113, 7, 2, 1, 1)
        self.label_114 = QtWidgets.QLabel(self.group_13)
        self.label_114.setMaximumSize(QtCore.QSize(20, 20))
        self.label_114.setText("")
        self.label_114.setPixmap(self.helpIcon)
        self.label_114.setScaledContents(True)
        self.label_114.setObjectName("label_114")
        self.gridLayout_13.addWidget(self.label_114, 8, 2, 1, 1)
        self.horizontalLayout_11.addLayout(self.gridLayout_13)
        self.verticalLayout_9.addWidget(self.group_13)
        tabObj.addTab(self.tabStep_5, "")

    #初始化控件信号槽
    def connectSignal(self, mainWidget):
        # 绑定切换页签的信号槽
        self.tabWidget.currentChanged[int].connect(self.buttonChange)
        # 定义Next按钮信号槽
        self.confirmBtn.clicked.connect(lambda: self.nextClicked(self.tabWidget.currentIndex(), self.tabWidget))
        # Cancel按钮信号绑定退出槽函数
        self.cancelBtn.clicked.connect(mainWidget.close)

    #更改Next按钮显示的槽函数
    def buttonChange(self, pos):
        if (pos > (self.tabWidget.count() - 2) ):
            self.confirmBtn.setText('完成')
        else:
            self.confirmBtn.setText('Next')

    #下一步切换tab的槽函数
    def nextClicked(self, pos, tabObj):
        #改变按钮显示
        self.buttonChange(pos)
        if(pos < (tabObj.count() - 1) ):
            if(pos == 0):
                print('抽取数据库完成')
            elif(pos == 1):
                print('系统数据库完成')
            elif(pos == 2):
                print('Nifi配置完成')
            elif (pos == 3):
                print('Nifi配置完成')
            else:
                print('工厂定制配置完成')
            tabObj.setCurrentIndex(pos + 1)
        else:
            print('完成')

