# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'home.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_mainWidget(object):
    def setupUi(self, mainWidget):
        mainWidget.setObjectName("mainWidget")
        mainWidget.resize(500, 640)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:/Users/slave/Desktop/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        mainWidget.setWindowIcon(icon)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(mainWidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(mainWidget)
        self.tabWidget.setObjectName("tabWidget")

        self.tabStep_1 = QtWidgets.QWidget()
        self.tabStep_1.setObjectName("tabStep_1")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tabStep_1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.group_1 = QtWidgets.QGroupBox(self.tabStep_1)
        self.group_1.setObjectName("group_1")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.group_1)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setContentsMargins(10, -1, 10, -1)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_76 = QtWidgets.QLabel(self.group_1)
        self.label_76.setAlignment(QtCore.Qt.AlignCenter)
        self.label_76.setObjectName("label_76")
        self.gridLayout_8.addWidget(self.label_76, 1, 0, 1, 1)
        self.input_3 = QtWidgets.QLineEdit(self.group_1)
        self.input_3.setObjectName("input_3")
        self.gridLayout_8.addWidget(self.input_3, 1, 1, 1, 1)
        self.label_77 = QtWidgets.QLabel(self.group_1)
        self.label_77.setAlignment(QtCore.Qt.AlignCenter)
        self.label_77.setObjectName("label_77")
        self.gridLayout_8.addWidget(self.label_77, 2, 0, 1, 1)
        self.help_2 = QtWidgets.QLabel(self.group_1)
        self.help_2.setMaximumSize(QtCore.QSize(20, 20))
        self.help_2.setText("")
        self.help_2.setPixmap(QtGui.QPixmap("C:/Users/slave/Desktop/help.png"))
        self.help_2.setScaledContents(True)
        self.help_2.setObjectName("help_2")
        self.gridLayout_8.addWidget(self.help_2, 1, 4, 1, 1)
        self.label_72 = QtWidgets.QLabel(self.group_1)
        self.label_72.setAlignment(QtCore.Qt.AlignCenter)
        self.label_72.setObjectName("label_72")
        self.gridLayout_8.addWidget(self.label_72, 0, 2, 1, 1)
        self.label_73 = QtWidgets.QLabel(self.group_1)
        self.label_73.setAlignment(QtCore.Qt.AlignCenter)
        self.label_73.setObjectName("label_73")
        self.gridLayout_8.addWidget(self.label_73, 1, 2, 1, 1)
        self.label_78 = QtWidgets.QLabel(self.group_1)
        self.label_78.setAlignment(QtCore.Qt.AlignCenter)
        self.label_78.setObjectName("label_78")
        self.gridLayout_8.addWidget(self.label_78, 0, 0, 1, 1)
        self.help_1 = QtWidgets.QLabel(self.group_1)
        self.help_1.setMaximumSize(QtCore.QSize(20, 20))
        self.help_1.setText("")
        self.help_1.setPixmap(QtGui.QPixmap("C:/Users/slave/Desktop/help.png"))
        self.help_1.setScaledContents(True)
        self.help_1.setObjectName("help_1")
        self.gridLayout_8.addWidget(self.help_1, 0, 4, 1, 1)
        self.help_3 = QtWidgets.QLabel(self.group_1)
        self.help_3.setMaximumSize(QtCore.QSize(20, 20))
        self.help_3.setText("")
        self.help_3.setPixmap(QtGui.QPixmap("C:/Users/slave/Desktop/help.png"))
        self.help_3.setScaledContents(True)
        self.help_3.setObjectName("help_3")
        self.gridLayout_8.addWidget(self.help_3, 2, 4, 1, 1)
        self.input_1 = QtWidgets.QLineEdit(self.group_1)
        self.input_1.setObjectName("input_1")
        self.gridLayout_8.addWidget(self.input_1, 0, 1, 1, 1)
        self.input_5 = QtWidgets.QComboBox(self.group_1)
        self.input_5.setObjectName("input_5")
        self.input_5.addItem("")
        self.gridLayout_8.addWidget(self.input_5, 2, 1, 1, 2)
        self.input_2 = QtWidgets.QLineEdit(self.group_1)
        self.input_2.setObjectName("input_2")
        self.gridLayout_8.addWidget(self.input_2, 0, 3, 1, 1)
        self.input_4 = QtWidgets.QLineEdit(self.group_1)
        self.input_4.setObjectName("input_4")
        self.gridLayout_8.addWidget(self.input_4, 1, 3, 1, 1)
        self.getDBBtn_1 = QtWidgets.QPushButton(self.group_1)
        self.getDBBtn_1.setMaximumSize(QtCore.QSize(50, 16777215))
        self.getDBBtn_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.getDBBtn_1.setAutoDefault(False)
        self.getDBBtn_1.setDefault(False)
        self.getDBBtn_1.setFlat(False)
        self.getDBBtn_1.setObjectName("getDBBtn_1")
        self.gridLayout_8.addWidget(self.getDBBtn_1, 2, 3, 1, 1)
        self.gridLayout_8.setColumnStretch(1, 3)
        self.gridLayout_8.setColumnStretch(2, 1)
        self.gridLayout_8.setColumnStretch(3, 3)
        self.horizontalLayout_8.addLayout(self.gridLayout_8)
        self.verticalLayout_3.addWidget(self.group_1)
        self.group_2 = QtWidgets.QGroupBox(self.tabStep_1)
        self.group_2.setObjectName("group_2")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.group_2)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setContentsMargins(10, -1, 10, -1)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_85 = QtWidgets.QLabel(self.group_2)
        self.label_85.setAlignment(QtCore.Qt.AlignCenter)
        self.label_85.setObjectName("label_85")
        self.gridLayout_9.addWidget(self.label_85, 3, 0, 1, 1)
        self.input_7 = QtWidgets.QLineEdit(self.group_2)
        self.input_7.setEnabled(True)
        self.input_7.setObjectName("input_7")
        self.gridLayout_9.addWidget(self.input_7, 1, 1, 1, 1)
        self.label_81 = QtWidgets.QLabel(self.group_2)
        self.label_81.setAlignment(QtCore.Qt.AlignCenter)
        self.label_81.setObjectName("label_81")
        self.gridLayout_9.addWidget(self.label_81, 2, 2, 1, 1)
        self.input_9 = QtWidgets.QLineEdit(self.group_2)
        self.input_9.setObjectName("input_9")
        self.gridLayout_9.addWidget(self.input_9, 2, 1, 1, 1)
        self.label_86 = QtWidgets.QLabel(self.group_2)
        self.label_86.setAlignment(QtCore.Qt.AlignCenter)
        self.label_86.setObjectName("label_86")
        self.gridLayout_9.addWidget(self.label_86, 1, 0, 1, 1)
        self.help_7 = QtWidgets.QLabel(self.group_2)
        self.help_7.setMaximumSize(QtCore.QSize(20, 20))
        self.help_7.setText("")
        self.help_7.setPixmap(QtGui.QPixmap("C:/Users/slave/Desktop/help.png"))
        self.help_7.setScaledContents(True)
        self.help_7.setObjectName("help_7")
        self.gridLayout_9.addWidget(self.help_7, 3, 4, 1, 1)
        self.help_5 = QtWidgets.QLabel(self.group_2)
        self.help_5.setMaximumSize(QtCore.QSize(20, 20))
        self.help_5.setText("")
        self.help_5.setPixmap(QtGui.QPixmap("C:/Users/slave/Desktop/help.png"))
        self.help_5.setScaledContents(True)
        self.help_5.setObjectName("help_5")
        self.gridLayout_9.addWidget(self.help_5, 1, 4, 1, 1)
        self.input_8 = QtWidgets.QLineEdit(self.group_2)
        self.input_8.setObjectName("input_8")
        self.gridLayout_9.addWidget(self.input_8, 1, 3, 1, 1)
        self.input_10 = QtWidgets.QLineEdit(self.group_2)
        self.input_10.setObjectName("input_10")
        self.gridLayout_9.addWidget(self.input_10, 2, 3, 1, 1)
        self.help_6 = QtWidgets.QLabel(self.group_2)
        self.help_6.setMaximumSize(QtCore.QSize(20, 20))
        self.help_6.setText("")
        self.help_6.setPixmap(QtGui.QPixmap("C:/Users/slave/Desktop/help.png"))
        self.help_6.setScaledContents(True)
        self.help_6.setObjectName("help_6")
        self.gridLayout_9.addWidget(self.help_6, 2, 4, 1, 1)
        self.label_84 = QtWidgets.QLabel(self.group_2)
        self.label_84.setAlignment(QtCore.Qt.AlignCenter)
        self.label_84.setObjectName("label_84")
        self.gridLayout_9.addWidget(self.label_84, 2, 0, 1, 1)
        self.label_80 = QtWidgets.QLabel(self.group_2)
        self.label_80.setAlignment(QtCore.Qt.AlignCenter)
        self.label_80.setObjectName("label_80")
        self.gridLayout_9.addWidget(self.label_80, 1, 2, 1, 1)
        self.input_6 = QtWidgets.QCheckBox(self.group_2)
        self.input_6.setChecked(True)
        self.input_6.setObjectName("input_6")
        self.gridLayout_9.addWidget(self.input_6, 0, 0, 1, 4)
        self.help_4 = QtWidgets.QLabel(self.group_2)
        self.help_4.setMaximumSize(QtCore.QSize(20, 20))
        self.help_4.setText("")
        self.help_4.setPixmap(QtGui.QPixmap("C:/Users/slave/Desktop/help.png"))
        self.help_4.setScaledContents(True)
        self.help_4.setObjectName("help_4")
        self.gridLayout_9.addWidget(self.help_4, 0, 4, 1, 1)
        self.input_11 = QtWidgets.QComboBox(self.group_2)
        self.input_11.setEnabled(True)
        self.input_11.setObjectName("input_11")
        self.input_11.addItem("")
        self.gridLayout_9.addWidget(self.input_11, 3, 1, 1, 2)
        self.getDBBtn_2 = QtWidgets.QPushButton(self.group_2)
        self.getDBBtn_2.setMaximumSize(QtCore.QSize(50, 16777215))
        self.getDBBtn_2.setObjectName("getDBBtn_2")
        self.gridLayout_9.addWidget(self.getDBBtn_2, 3, 3, 1, 1)
        self.gridLayout_9.setColumnStretch(1, 3)
        self.gridLayout_9.setColumnStretch(2, 1)
        self.gridLayout_9.setColumnStretch(3, 3)
        self.horizontalLayout_9.addLayout(self.gridLayout_9)
        self.verticalLayout_3.addWidget(self.group_2)
        self.group_8 = QtWidgets.QGroupBox(self.tabStep_1)
        self.group_8.setObjectName("group_8")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.group_8)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.gridLayout_14 = QtWidgets.QGridLayout()
        self.gridLayout_14.setContentsMargins(10, -1, 10, -1)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.help_8 = QtWidgets.QLabel(self.group_8)
        self.help_8.setMaximumSize(QtCore.QSize(20, 20))
        self.help_8.setText("")
        self.help_8.setPixmap(QtGui.QPixmap("C:/Users/slave/Desktop/help.png"))
        self.help_8.setScaledContents(True)
        self.help_8.setObjectName("help_8")
        self.gridLayout_14.addWidget(self.help_8, 0, 4, 1, 1)
        self.input_13 = QtWidgets.QLineEdit(self.group_8)
        self.input_13.setObjectName("input_13")
        self.gridLayout_14.addWidget(self.input_13, 0, 3, 1, 1)
        self.label_116 = QtWidgets.QLabel(self.group_8)
        self.label_116.setAlignment(QtCore.Qt.AlignCenter)
        self.label_116.setObjectName("label_116")
        self.gridLayout_14.addWidget(self.label_116, 1, 2, 1, 1)
        self.label_117 = QtWidgets.QLabel(self.group_8)
        self.label_117.setAlignment(QtCore.Qt.AlignCenter)
        self.label_117.setObjectName("label_117")
        self.gridLayout_14.addWidget(self.label_117, 0, 2, 1, 1)
        self.help_9 = QtWidgets.QLabel(self.group_8)
        self.help_9.setMaximumSize(QtCore.QSize(20, 20))
        self.help_9.setText("")
        self.help_9.setPixmap(QtGui.QPixmap("C:/Users/slave/Desktop/help.png"))
        self.help_9.setScaledContents(True)
        self.help_9.setObjectName("help_9")
        self.gridLayout_14.addWidget(self.help_9, 1, 4, 1, 1)
        self.help_10 = QtWidgets.QLabel(self.group_8)
        self.help_10.setMaximumSize(QtCore.QSize(20, 20))
        self.help_10.setText("")
        self.help_10.setPixmap(QtGui.QPixmap("C:/Users/slave/Desktop/help.png"))
        self.help_10.setScaledContents(True)
        self.help_10.setObjectName("help_10")
        self.gridLayout_14.addWidget(self.help_10, 2, 4, 1, 1)
        self.input_12 = QtWidgets.QLineEdit(self.group_8)
        self.input_12.setObjectName("input_12")
        self.gridLayout_14.addWidget(self.input_12, 0, 1, 1, 1)
        self.label_120 = QtWidgets.QLabel(self.group_8)
        self.label_120.setAlignment(QtCore.Qt.AlignCenter)
        self.label_120.setObjectName("label_120")
        self.gridLayout_14.addWidget(self.label_120, 1, 0, 1, 1)
        self.label_121 = QtWidgets.QLabel(self.group_8)
        self.label_121.setAlignment(QtCore.Qt.AlignCenter)
        self.label_121.setObjectName("label_121")
        self.gridLayout_14.addWidget(self.label_121, 2, 0, 1, 1)
        self.label_122 = QtWidgets.QLabel(self.group_8)
        self.label_122.setAlignment(QtCore.Qt.AlignCenter)
        self.label_122.setObjectName("label_122")
        self.gridLayout_14.addWidget(self.label_122, 0, 0, 1, 1)
        self.input_16 = QtWidgets.QLineEdit(self.group_8)
        self.input_16.setObjectName("input_16")
        self.gridLayout_14.addWidget(self.input_16, 2, 1, 1, 3)
        self.input_14 = QtWidgets.QLineEdit(self.group_8)
        self.input_14.setObjectName("input_14")
        self.gridLayout_14.addWidget(self.input_14, 1, 1, 1, 1)
        self.input_15 = QtWidgets.QLineEdit(self.group_8)
        self.input_15.setObjectName("input_15")
        self.gridLayout_14.addWidget(self.input_15, 1, 3, 1, 1)
        self.label_123 = QtWidgets.QLabel(self.group_8)
        self.label_123.setAlignment(QtCore.Qt.AlignCenter)
        self.label_123.setObjectName("label_123")
        self.gridLayout_14.addWidget(self.label_123, 3, 0, 1, 1)
        self.input_17 = QtWidgets.QLineEdit(self.group_8)
        self.input_17.setEnabled(True)
        self.input_17.setObjectName("input_17")
        self.gridLayout_14.addWidget(self.input_17, 3, 1, 1, 1)
        self.label_124 = QtWidgets.QLabel(self.group_8)
        self.label_124.setAlignment(QtCore.Qt.AlignCenter)
        self.label_124.setObjectName("label_124")
        self.gridLayout_14.addWidget(self.label_124, 3, 2, 1, 1)
        self.input_18 = QtWidgets.QLineEdit(self.group_8)
        self.input_18.setEnabled(True)
        self.input_18.setObjectName("input_18")
        self.gridLayout_14.addWidget(self.input_18, 3, 3, 1, 1)
        self.help_11 = QtWidgets.QLabel(self.group_8)
        self.help_11.setMaximumSize(QtCore.QSize(20, 20))
        self.help_11.setText("")
        self.help_11.setPixmap(QtGui.QPixmap("C:/Users/slave/Desktop/help.png"))
        self.help_11.setScaledContents(True)
        self.help_11.setObjectName("help_11")
        self.gridLayout_14.addWidget(self.help_11, 3, 4, 1, 1)
        self.gridLayout_14.setColumnStretch(1, 3)
        self.gridLayout_14.setColumnStretch(2, 1)
        self.gridLayout_14.setColumnStretch(3, 3)
        self.horizontalLayout_13.addLayout(self.gridLayout_14)
        self.verticalLayout_3.addWidget(self.group_8)
        self.group_3 = QtWidgets.QGroupBox(self.tabStep_1)
        self.group_3.setObjectName("group_3")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.group_3)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setContentsMargins(10, -1, 10, -1)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_64 = QtWidgets.QLabel(self.group_3)
        self.label_64.setAlignment(QtCore.Qt.AlignCenter)
        self.label_64.setObjectName("label_64")
        self.gridLayout_7.addWidget(self.label_64, 0, 2, 1, 1)
        self.label_65 = QtWidgets.QLabel(self.group_3)
        self.label_65.setAlignment(QtCore.Qt.AlignCenter)
        self.label_65.setObjectName("label_65")
        self.gridLayout_7.addWidget(self.label_65, 1, 2, 1, 1)
        self.input_19 = QtWidgets.QLineEdit(self.group_3)
        self.input_19.setObjectName("input_19")
        self.gridLayout_7.addWidget(self.input_19, 0, 1, 1, 1)
        self.help_13 = QtWidgets.QLabel(self.group_3)
        self.help_13.setMaximumSize(QtCore.QSize(20, 20))
        self.help_13.setText("")
        self.help_13.setPixmap(QtGui.QPixmap("C:/Users/slave/Desktop/help.png"))
        self.help_13.setScaledContents(True)
        self.help_13.setObjectName("help_13")
        self.gridLayout_7.addWidget(self.help_13, 1, 4, 1, 1)
        self.help_14 = QtWidgets.QLabel(self.group_3)
        self.help_14.setMaximumSize(QtCore.QSize(20, 20))
        self.help_14.setText("")
        self.help_14.setPixmap(QtGui.QPixmap("C:/Users/slave/Desktop/help.png"))
        self.help_14.setScaledContents(True)
        self.help_14.setObjectName("help_14")
        self.gridLayout_7.addWidget(self.help_14, 2, 4, 1, 1)
        self.label_68 = QtWidgets.QLabel(self.group_3)
        self.label_68.setAlignment(QtCore.Qt.AlignCenter)
        self.label_68.setObjectName("label_68")
        self.gridLayout_7.addWidget(self.label_68, 1, 0, 1, 1)
        self.label_69 = QtWidgets.QLabel(self.group_3)
        self.label_69.setAlignment(QtCore.Qt.AlignCenter)
        self.label_69.setObjectName("label_69")
        self.gridLayout_7.addWidget(self.label_69, 2, 0, 1, 1)
        self.label_70 = QtWidgets.QLabel(self.group_3)
        self.label_70.setAlignment(QtCore.Qt.AlignCenter)
        self.label_70.setObjectName("label_70")
        self.gridLayout_7.addWidget(self.label_70, 0, 0, 1, 1)
        self.help_12 = QtWidgets.QLabel(self.group_3)
        self.help_12.setMaximumSize(QtCore.QSize(20, 20))
        self.help_12.setText("")
        self.help_12.setPixmap(QtGui.QPixmap("C:/Users/slave/Desktop/help.png"))
        self.help_12.setScaledContents(True)
        self.help_12.setObjectName("help_12")
        self.gridLayout_7.addWidget(self.help_12, 0, 4, 1, 1)
        self.input_20 = QtWidgets.QLineEdit(self.group_3)
        self.input_20.setObjectName("input_20")
        self.gridLayout_7.addWidget(self.input_20, 0, 3, 1, 1)
        self.input_23 = QtWidgets.QLineEdit(self.group_3)
        self.input_23.setObjectName("input_23")
        self.gridLayout_7.addWidget(self.input_23, 2, 1, 1, 3)
        self.input_21 = QtWidgets.QLineEdit(self.group_3)
        self.input_21.setObjectName("input_21")
        self.gridLayout_7.addWidget(self.input_21, 1, 1, 1, 1)
        self.input_22 = QtWidgets.QLineEdit(self.group_3)
        self.input_22.setObjectName("input_22")
        self.gridLayout_7.addWidget(self.input_22, 1, 3, 1, 1)
        self.gridLayout_7.setColumnStretch(1, 3)
        self.gridLayout_7.setColumnStretch(2, 1)
        self.gridLayout_7.setColumnStretch(3, 3)
        self.horizontalLayout_7.addLayout(self.gridLayout_7)
        self.verticalLayout_3.addWidget(self.group_3)
        self.verticalLayout_3.setStretch(0, 3)
        self.verticalLayout_3.setStretch(1, 4)
        self.verticalLayout_3.setStretch(2, 4)
        self.verticalLayout_3.setStretch(3, 3)
        self.tabWidget.addTab(self.tabStep_1, "")

        self.tabStep_2 = QtWidgets.QWidget()
        self.tabStep_2.setObjectName("tabStep_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tabStep_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.group_14 = QtWidgets.QGroupBox(self.tabStep_2)
        self.group_14.setObjectName("group_14")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.group_14)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setContentsMargins(10, -1, 10, -1)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_126 = QtWidgets.QLabel(self.group_14)
        self.label_126.setAlignment(QtCore.Qt.AlignCenter)
        self.label_126.setObjectName("label_126")
        self.gridLayout_5.addWidget(self.label_126, 3, 2, 1, 1)
        self.help_17 = QtWidgets.QLabel(self.group_14)
        self.help_17.setMaximumSize(QtCore.QSize(20, 20))
        self.help_17.setText("")
        self.help_17.setPixmap(QtGui.QPixmap("C:/Users/slave/Desktop/help.png"))
        self.help_17.setScaledContents(True)
        self.help_17.setObjectName("help_17")
        self.gridLayout_5.addWidget(self.help_17, 2, 4, 1, 1)
        self.label_38 = QtWidgets.QLabel(self.group_14)
        self.label_38.setAlignment(QtCore.Qt.AlignCenter)
        self.label_38.setObjectName("label_38")
        self.gridLayout_5.addWidget(self.label_38, 3, 0, 1, 1)
        self.label_41 = QtWidgets.QLabel(self.group_14)
        self.label_41.setAlignment(QtCore.Qt.AlignCenter)
        self.label_41.setObjectName("label_41")
        self.gridLayout_5.addWidget(self.label_41, 2, 0, 1, 1)
        self.help_18 = QtWidgets.QLabel(self.group_14)
        self.help_18.setMaximumSize(QtCore.QSize(20, 20))
        self.help_18.setText("")
        self.help_18.setPixmap(QtGui.QPixmap("C:/Users/slave/Desktop/help.png"))
        self.help_18.setScaledContents(True)
        self.help_18.setObjectName("help_18")
        self.gridLayout_5.addWidget(self.help_18, 3, 4, 1, 1)
        self.label_43 = QtWidgets.QLabel(self.group_14)
        self.label_43.setAlignment(QtCore.Qt.AlignCenter)
        self.label_43.setObjectName("label_43")
        self.gridLayout_5.addWidget(self.label_43, 1, 0, 1, 1)
        self.help_16 = QtWidgets.QLabel(self.group_14)
        self.help_16.setMaximumSize(QtCore.QSize(20, 20))
        self.help_16.setText("")
        self.help_16.setPixmap(QtGui.QPixmap("C:/Users/slave/Desktop/help.png"))
        self.help_16.setScaledContents(True)
        self.help_16.setObjectName("help_16")
        self.gridLayout_5.addWidget(self.help_16, 1, 4, 1, 1)
        self.input_27 = QtWidgets.QLineEdit(self.group_14)
        self.input_27.setObjectName("input_27")
        self.gridLayout_5.addWidget(self.input_27, 3, 1, 1, 1)
        self.input_28 = QtWidgets.QLineEdit(self.group_14)
        self.input_28.setObjectName("input_28")
        self.gridLayout_5.addWidget(self.input_28, 3, 3, 1, 1)
        self.input_25 = QtWidgets.QLineEdit(self.group_14)
        self.input_25.setObjectName("input_25")
        self.gridLayout_5.addWidget(self.input_25, 1, 1, 1, 3)
        self.input_26 = QtWidgets.QLineEdit(self.group_14)
        self.input_26.setObjectName("input_26")
        self.gridLayout_5.addWidget(self.input_26, 2, 1, 1, 3)
        self.input_24 = QtWidgets.QCheckBox(self.group_14)
        self.input_24.setChecked(True)
        self.input_24.setObjectName("input_24")
        self.gridLayout_5.addWidget(self.input_24, 0, 0, 1, 4)
        self.help_15 = QtWidgets.QLabel(self.group_14)
        self.help_15.setMaximumSize(QtCore.QSize(20, 20))
        self.help_15.setText("")
        self.help_15.setPixmap(QtGui.QPixmap("C:/Users/slave/Desktop/help.png"))
        self.help_15.setScaledContents(True)
        self.help_15.setObjectName("help_15")
        self.gridLayout_5.addWidget(self.help_15, 0, 4, 1, 1)
        self.gridLayout_5.setColumnStretch(0, 1)
        self.gridLayout_5.setColumnStretch(1, 3)
        self.gridLayout_5.setColumnStretch(2, 1)
        self.horizontalLayout_14.addLayout(self.gridLayout_5)
        self.verticalLayout_4.addWidget(self.group_14)
        self.group_5 = QtWidgets.QGroupBox(self.tabStep_2)
        self.group_5.setObjectName("group_5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.group_5)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setContentsMargins(10, -1, 10, -1)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.input_34 = QtWidgets.QLineEdit(self.group_5)
        self.input_34.setObjectName("input_34")
        self.gridLayout_6.addWidget(self.input_34, 3, 1, 1, 3)
        self.label_55 = QtWidgets.QLabel(self.group_5)
        self.label_55.setAlignment(QtCore.Qt.AlignCenter)
        self.label_55.setObjectName("label_55")
        self.gridLayout_6.addWidget(self.label_55, 3, 0, 1, 1)
        self.label_51 = QtWidgets.QLabel(self.group_5)
        self.label_51.setAlignment(QtCore.Qt.AlignCenter)
        self.label_51.setObjectName("label_51")
        self.gridLayout_6.addWidget(self.label_51, 1, 0, 1, 1)
        self.label_48 = QtWidgets.QLabel(self.group_5)
        self.label_48.setAlignment(QtCore.Qt.AlignCenter)
        self.label_48.setObjectName("label_48")
        self.gridLayout_6.addWidget(self.label_48, 1, 2, 1, 1)
        self.label_47 = QtWidgets.QLabel(self.group_5)
        self.label_47.setAlignment(QtCore.Qt.AlignCenter)
        self.label_47.setObjectName("label_47")
        self.gridLayout_6.addWidget(self.label_47, 0, 2, 1, 1)
        self.label_53 = QtWidgets.QLabel(self.group_5)
        self.label_53.setAlignment(QtCore.Qt.AlignCenter)
        self.label_53.setObjectName("label_53")
        self.gridLayout_6.addWidget(self.label_53, 0, 0, 1, 1)
        self.help_19 = QtWidgets.QLabel(self.group_5)
        self.help_19.setMaximumSize(QtCore.QSize(20, 20))
        self.help_19.setText("")
        self.help_19.setPixmap(QtGui.QPixmap("C:/Users/slave/Desktop/help.png"))
        self.help_19.setScaledContents(True)
        self.help_19.setObjectName("help_19")
        self.gridLayout_6.addWidget(self.help_19, 0, 4, 1, 1)
        self.input_30 = QtWidgets.QLineEdit(self.group_5)
        self.input_30.setObjectName("input_30")
        self.gridLayout_6.addWidget(self.input_30, 0, 3, 1, 1)
        self.label_52 = QtWidgets.QLabel(self.group_5)
        self.label_52.setAlignment(QtCore.Qt.AlignCenter)
        self.label_52.setObjectName("label_52")
        self.gridLayout_6.addWidget(self.label_52, 2, 0, 1, 1)
        self.input_31 = QtWidgets.QLineEdit(self.group_5)
        self.input_31.setObjectName("input_31")
        self.gridLayout_6.addWidget(self.input_31, 1, 1, 1, 1)
        self.input_32 = QtWidgets.QLineEdit(self.group_5)
        self.input_32.setObjectName("input_32")
        self.gridLayout_6.addWidget(self.input_32, 1, 3, 1, 1)
        self.help_20 = QtWidgets.QLabel(self.group_5)
        self.help_20.setMaximumSize(QtCore.QSize(20, 20))
        self.help_20.setText("")
        self.help_20.setPixmap(QtGui.QPixmap("C:/Users/slave/Desktop/help.png"))
        self.help_20.setScaledContents(True)
        self.help_20.setObjectName("help_20")
        self.gridLayout_6.addWidget(self.help_20, 1, 4, 1, 1)
        self.input_29 = QtWidgets.QLineEdit(self.group_5)
        self.input_29.setObjectName("input_29")
        self.gridLayout_6.addWidget(self.input_29, 0, 1, 1, 1)
        self.input_33 = QtWidgets.QLineEdit(self.group_5)
        self.input_33.setObjectName("input_33")
        self.gridLayout_6.addWidget(self.input_33, 2, 1, 1, 3)
        self.help_21 = QtWidgets.QLabel(self.group_5)
        self.help_21.setMaximumSize(QtCore.QSize(20, 20))
        self.help_21.setText("")
        self.help_21.setPixmap(QtGui.QPixmap("C:/Users/slave/Desktop/help.png"))
        self.help_21.setScaledContents(True)
        self.help_21.setObjectName("help_21")
        self.gridLayout_6.addWidget(self.help_21, 2, 4, 1, 1)
        self.label_56 = QtWidgets.QLabel(self.group_5)
        self.label_56.setAlignment(QtCore.Qt.AlignCenter)
        self.label_56.setObjectName("label_56")
        self.gridLayout_6.addWidget(self.label_56, 4, 0, 1, 1)
        self.label_57 = QtWidgets.QLabel(self.group_5)
        self.label_57.setAlignment(QtCore.Qt.AlignCenter)
        self.label_57.setObjectName("label_57")
        self.gridLayout_6.addWidget(self.label_57, 5, 0, 1, 1)
        self.input_35 = QtWidgets.QLineEdit(self.group_5)
        self.input_35.setObjectName("input_35")
        self.gridLayout_6.addWidget(self.input_35, 4, 1, 1, 1)
        self.input_36 = QtWidgets.QLineEdit(self.group_5)
        self.input_36.setObjectName("input_36")
        self.gridLayout_6.addWidget(self.input_36, 4, 3, 1, 1)
        self.input_37 = QtWidgets.QLineEdit(self.group_5)
        self.input_37.setObjectName("input_37")
        self.gridLayout_6.addWidget(self.input_37, 5, 1, 1, 1)
        self.input_38 = QtWidgets.QLineEdit(self.group_5)
        self.input_38.setObjectName("input_38")
        self.gridLayout_6.addWidget(self.input_38, 5, 3, 1, 1)
        self.label_58 = QtWidgets.QLabel(self.group_5)
        self.label_58.setAlignment(QtCore.Qt.AlignCenter)
        self.label_58.setObjectName("label_58")
        self.gridLayout_6.addWidget(self.label_58, 4, 2, 1, 1)
        self.label_59 = QtWidgets.QLabel(self.group_5)
        self.label_59.setAlignment(QtCore.Qt.AlignCenter)
        self.label_59.setObjectName("label_59")
        self.gridLayout_6.addWidget(self.label_59, 5, 2, 1, 1)
        self.help_22 = QtWidgets.QLabel(self.group_5)
        self.help_22.setMaximumSize(QtCore.QSize(20, 20))
        self.help_22.setText("")
        self.help_22.setPixmap(QtGui.QPixmap("C:/Users/slave/Desktop/help.png"))
        self.help_22.setScaledContents(True)
        self.help_22.setObjectName("help_22")
        self.gridLayout_6.addWidget(self.help_22, 3, 4, 1, 1)
        self.help_23 = QtWidgets.QLabel(self.group_5)
        self.help_23.setMaximumSize(QtCore.QSize(20, 20))
        self.help_23.setText("")
        self.help_23.setPixmap(QtGui.QPixmap("C:/Users/slave/Desktop/help.png"))
        self.help_23.setScaledContents(True)
        self.help_23.setObjectName("help_23")
        self.gridLayout_6.addWidget(self.help_23, 4, 4, 1, 1)
        self.help_24 = QtWidgets.QLabel(self.group_5)
        self.help_24.setMaximumSize(QtCore.QSize(20, 20))
        self.help_24.setText("")
        self.help_24.setPixmap(QtGui.QPixmap("C:/Users/slave/Desktop/help.png"))
        self.help_24.setScaledContents(True)
        self.help_24.setObjectName("help_24")
        self.gridLayout_6.addWidget(self.help_24, 5, 4, 1, 1)
        self.gridLayout_6.setColumnStretch(1, 3)
        self.gridLayout_6.setColumnStretch(2, 1)
        self.gridLayout_6.setColumnStretch(3, 3)
        self.horizontalLayout_6.addLayout(self.gridLayout_6)
        self.verticalLayout_4.addWidget(self.group_5)
        self.verticalLayout_4.setStretch(0, 4)
        self.verticalLayout_4.setStretch(1, 6)
        self.tabWidget.addTab(self.tabStep_2, "")
        self.tabStep_3 = QtWidgets.QWidget()
        self.tabStep_3.setObjectName("tabStep_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tabStep_3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.group_6 = QtWidgets.QGroupBox(self.tabStep_3)
        self.group_6.setObjectName("group_6")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.group_6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setContentsMargins(10, -1, 10, -1)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.help_27 = QtWidgets.QLabel(self.group_6)
        self.help_27.setMaximumSize(QtCore.QSize(20, 20))
        self.help_27.setText("")
        self.help_27.setPixmap(QtGui.QPixmap("C:/Users/slave/Desktop/help.png"))
        self.help_27.setScaledContents(True)
        self.help_27.setObjectName("help_27")
        self.gridLayout_3.addWidget(self.help_27, 2, 2, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.group_6)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout_3.addWidget(self.label_15, 0, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.group_6)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.gridLayout_3.addWidget(self.label_18, 1, 0, 1, 1)
        self.help_26 = QtWidgets.QLabel(self.group_6)
        self.help_26.setMaximumSize(QtCore.QSize(20, 20))
        self.help_26.setText("")
        self.help_26.setPixmap(QtGui.QPixmap("C:/Users/slave/Desktop/help.png"))
        self.help_26.setScaledContents(True)
        self.help_26.setObjectName("help_26")
        self.gridLayout_3.addWidget(self.help_26, 1, 2, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.group_6)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout_3.addWidget(self.label_16, 2, 0, 1, 1)
        self.help_25 = QtWidgets.QLabel(self.group_6)
        self.help_25.setMaximumSize(QtCore.QSize(20, 20))
        self.help_25.setText("")
        self.help_25.setPixmap(QtGui.QPixmap("C:/Users/slave/Desktop/help.png"))
        self.help_25.setScaledContents(True)
        self.help_25.setObjectName("help_25")
        self.gridLayout_3.addWidget(self.help_25, 0, 2, 1, 1)
        self.input_39 = QtWidgets.QLineEdit(self.group_6)
        self.input_39.setObjectName("input_39")
        self.gridLayout_3.addWidget(self.input_39, 0, 1, 1, 1)
        self.input_40 = QtWidgets.QLineEdit(self.group_6)
        self.input_40.setObjectName("input_40")
        self.gridLayout_3.addWidget(self.input_40, 1, 1, 1, 1)
        self.input_41 = QtWidgets.QLineEdit(self.group_6)
        self.input_41.setObjectName("input_41")
        self.gridLayout_3.addWidget(self.input_41, 2, 1, 1, 1)
        self.gridLayout_3.setColumnStretch(0, 1)
        self.gridLayout_3.setColumnStretch(1, 3)
        self.gridLayout_3.setColumnStretch(2, 1)
        self.horizontalLayout_4.addLayout(self.gridLayout_3)
        self.verticalLayout_5.addWidget(self.group_6)
        self.group_7 = QtWidgets.QGroupBox(self.tabStep_3)
        self.group_7.setObjectName("group_7")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.group_7)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(10, -1, 10, -1)
        self.gridLayout.setObjectName("gridLayout")
        self.help_30 = QtWidgets.QLabel(self.group_7)
        self.help_30.setMaximumSize(QtCore.QSize(20, 20))
        self.help_30.setText("")
        self.help_30.setPixmap(QtGui.QPixmap("C:/Users/slave/Desktop/help.png"))
        self.help_30.setScaledContents(True)
        self.help_30.setObjectName("help_30")
        self.gridLayout.addWidget(self.help_30, 2, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.group_7)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.input_43 = QtWidgets.QLineEdit(self.group_7)
        self.input_43.setObjectName("input_43")
        self.gridLayout.addWidget(self.input_43, 1, 1, 1, 1)
        self.input_42 = QtWidgets.QLineEdit(self.group_7)
        self.input_42.setObjectName("input_42")
        self.gridLayout.addWidget(self.input_42, 0, 1, 1, 1)
        self.input_44 = QtWidgets.QLineEdit(self.group_7)
        self.input_44.setObjectName("input_44")
        self.gridLayout.addWidget(self.input_44, 2, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.group_7)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1)
        self.help_29 = QtWidgets.QLabel(self.group_7)
        self.help_29.setMaximumSize(QtCore.QSize(20, 20))
        self.help_29.setText("")
        self.help_29.setPixmap(QtGui.QPixmap("C:/Users/slave/Desktop/help.png"))
        self.help_29.setScaledContents(True)
        self.help_29.setObjectName("help_29")
        self.gridLayout.addWidget(self.help_29, 1, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.group_7)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.help_28 = QtWidgets.QLabel(self.group_7)
        self.help_28.setMaximumSize(QtCore.QSize(20, 20))
        self.help_28.setText("")
        self.help_28.setPixmap(QtGui.QPixmap("C:/Users/slave/Desktop/help.png"))
        self.help_28.setScaledContents(True)
        self.help_28.setObjectName("help_28")
        self.gridLayout.addWidget(self.help_28, 0, 2, 1, 1)
        self.gridLayout.setColumnStretch(0, 1)
        self.gridLayout.setColumnStretch(1, 3)
        self.gridLayout.setColumnStretch(2, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout)
        self.verticalLayout_5.addWidget(self.group_7)
        self.group8 = QtWidgets.QGroupBox(self.tabStep_3)
        self.group8.setObjectName("group8")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.group8)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setContentsMargins(10, -1, 10, -1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.help_33 = QtWidgets.QLabel(self.group8)
        self.help_33.setMaximumSize(QtCore.QSize(20, 20))
        self.help_33.setText("")
        self.help_33.setPixmap(QtGui.QPixmap("C:/Users/slave/Desktop/help.png"))
        self.help_33.setScaledContents(True)
        self.help_33.setObjectName("help_33")
        self.gridLayout_2.addWidget(self.help_33, 2, 2, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.group8)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 0, 0, 1, 1)
        self.input_46 = QtWidgets.QLineEdit(self.group8)
        self.input_46.setObjectName("input_46")
        self.gridLayout_2.addWidget(self.input_46, 1, 1, 1, 1)
        self.input_45 = QtWidgets.QLineEdit(self.group8)
        self.input_45.setObjectName("input_45")
        self.gridLayout_2.addWidget(self.input_45, 0, 1, 1, 1)
        self.input_47 = QtWidgets.QLineEdit(self.group8)
        self.input_47.setObjectName("input_47")
        self.gridLayout_2.addWidget(self.input_47, 2, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.group8)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 2, 0, 1, 1)
        self.help_32 = QtWidgets.QLabel(self.group8)
        self.help_32.setMaximumSize(QtCore.QSize(20, 20))
        self.help_32.setText("")
        self.help_32.setPixmap(QtGui.QPixmap("C:/Users/slave/Desktop/help.png"))
        self.help_32.setScaledContents(True)
        self.help_32.setObjectName("help_32")
        self.gridLayout_2.addWidget(self.help_32, 1, 2, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.group8)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 1, 0, 1, 1)
        self.help_31 = QtWidgets.QLabel(self.group8)
        self.help_31.setMaximumSize(QtCore.QSize(20, 20))
        self.help_31.setText("")
        self.help_31.setPixmap(QtGui.QPixmap("C:/Users/slave/Desktop/help.png"))
        self.help_31.setScaledContents(True)
        self.help_31.setObjectName("help_31")
        self.gridLayout_2.addWidget(self.help_31, 0, 2, 1, 1)
        self.gridLayout_2.setColumnStretch(0, 1)
        self.gridLayout_2.setColumnStretch(1, 3)
        self.gridLayout_2.setColumnStretch(2, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout_2)
        self.verticalLayout_5.addWidget(self.group8)
        self.tabWidget.addTab(self.tabStep_3, "")
        self.tabStep_4 = QtWidgets.QWidget()
        self.tabStep_4.setObjectName("tabStep_4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tabStep_4)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.group_9 = QtWidgets.QGroupBox(self.tabStep_4)
        self.group_9.setObjectName("group_9")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.group_9)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.gridLayout_12 = QtWidgets.QGridLayout()
        self.gridLayout_12.setContentsMargins(10, -1, 10, -1)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.label_95 = QtWidgets.QLabel(self.group_9)
        self.label_95.setAlignment(QtCore.Qt.AlignCenter)
        self.label_95.setObjectName("label_95")
        self.gridLayout_12.addWidget(self.label_95, 0, 0, 1, 1)
        self.input_48 = QtWidgets.QLineEdit(self.group_9)
        self.input_48.setObjectName("input_48")
        self.gridLayout_12.addWidget(self.input_48, 0, 1, 1, 1)
        self.help_34 = QtWidgets.QLabel(self.group_9)
        self.help_34.setMaximumSize(QtCore.QSize(20, 20))
        self.help_34.setText("")
        self.help_34.setPixmap(QtGui.QPixmap("C:/Users/slave/Desktop/help.png"))
        self.help_34.setScaledContents(True)
        self.help_34.setObjectName("help_34")
        self.gridLayout_12.addWidget(self.help_34, 0, 2, 1, 1)
        self.gridLayout_12.setColumnStretch(0, 1)
        self.gridLayout_12.setColumnStretch(1, 3)
        self.gridLayout_12.setColumnStretch(2, 1)
        self.horizontalLayout_12.addLayout(self.gridLayout_12)
        self.verticalLayout_6.addWidget(self.group_9)
        self.group_11 = QtWidgets.QGroupBox(self.tabStep_4)
        self.group_11.setObjectName("group_11")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.group_11)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setContentsMargins(10, -1, 10, -1)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.help_35 = QtWidgets.QLabel(self.group_11)
        self.help_35.setMaximumSize(QtCore.QSize(20, 20))
        self.help_35.setText("")
        self.help_35.setPixmap(QtGui.QPixmap("C:/Users/slave/Desktop/help.png"))
        self.help_35.setScaledContents(True)
        self.help_35.setObjectName("help_35")
        self.gridLayout_4.addWidget(self.help_35, 0, 2, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.group_11)
        self.label_29.setAlignment(QtCore.Qt.AlignCenter)
        self.label_29.setObjectName("label_29")
        self.gridLayout_4.addWidget(self.label_29, 1, 0, 1, 1)
        self.input_50 = QtWidgets.QLineEdit(self.group_11)
        self.input_50.setObjectName("input_50")
        self.gridLayout_4.addWidget(self.input_50, 1, 1, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.group_11)
        self.label_31.setAlignment(QtCore.Qt.AlignCenter)
        self.label_31.setObjectName("label_31")
        self.gridLayout_4.addWidget(self.label_31, 2, 0, 1, 1)
        self.help_36 = QtWidgets.QLabel(self.group_11)
        self.help_36.setMaximumSize(QtCore.QSize(20, 20))
        self.help_36.setText("")
        self.help_36.setPixmap(QtGui.QPixmap("C:/Users/slave/Desktop/help.png"))
        self.help_36.setScaledContents(True)
        self.help_36.setObjectName("help_36")
        self.gridLayout_4.addWidget(self.help_36, 1, 2, 1, 1)
        self.input_51 = QtWidgets.QLineEdit(self.group_11)
        self.input_51.setObjectName("input_51")
        self.gridLayout_4.addWidget(self.input_51, 2, 1, 1, 1)
        self.help_37 = QtWidgets.QLabel(self.group_11)
        self.help_37.setMaximumSize(QtCore.QSize(20, 20))
        self.help_37.setText("")
        self.help_37.setPixmap(QtGui.QPixmap("C:/Users/slave/Desktop/help.png"))
        self.help_37.setScaledContents(True)
        self.help_37.setObjectName("help_37")
        self.gridLayout_4.addWidget(self.help_37, 2, 2, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.group_11)
        self.label_32.setAlignment(QtCore.Qt.AlignCenter)
        self.label_32.setObjectName("label_32")
        self.gridLayout_4.addWidget(self.label_32, 3, 0, 1, 1)
        self.input_52 = QtWidgets.QLineEdit(self.group_11)
        self.input_52.setObjectName("input_52")
        self.gridLayout_4.addWidget(self.input_52, 3, 1, 1, 1)
        self.input_49 = QtWidgets.QCheckBox(self.group_11)
        self.input_49.setChecked(True)
        self.input_49.setObjectName("input_49")
        self.gridLayout_4.addWidget(self.input_49, 0, 0, 1, 2)
        self.help_38 = QtWidgets.QLabel(self.group_11)
        self.help_38.setMaximumSize(QtCore.QSize(20, 20))
        self.help_38.setText("")
        self.help_38.setPixmap(QtGui.QPixmap("C:/Users/slave/Desktop/help.png"))
        self.help_38.setScaledContents(True)
        self.help_38.setObjectName("help_38")
        self.gridLayout_4.addWidget(self.help_38, 3, 2, 1, 1)
        self.gridLayout_4.setColumnStretch(0, 1)
        self.gridLayout_4.setColumnStretch(1, 3)
        self.gridLayout_4.setColumnStretch(2, 1)
        self.horizontalLayout_10.addLayout(self.gridLayout_4)
        self.verticalLayout_6.addWidget(self.group_11)
        self.group_12 = QtWidgets.QGroupBox(self.tabStep_4)
        self.group_12.setObjectName("group_12")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.group_12)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setContentsMargins(10, -1, 10, -1)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label_93 = QtWidgets.QLabel(self.group_12)
        self.label_93.setAlignment(QtCore.Qt.AlignCenter)
        self.label_93.setObjectName("label_93")
        self.gridLayout_10.addWidget(self.label_93, 5, 0, 1, 1)
        self.input_57 = QtWidgets.QCheckBox(self.group_12)
        self.input_57.setObjectName("input_57")
        self.gridLayout_10.addWidget(self.input_57, 4, 0, 1, 2)
        self.input_54 = QtWidgets.QLineEdit(self.group_12)
        self.input_54.setObjectName("input_54")
        self.gridLayout_10.addWidget(self.input_54, 1, 1, 1, 1)
        self.help_43 = QtWidgets.QLabel(self.group_12)
        self.help_43.setMaximumSize(QtCore.QSize(20, 20))
        self.help_43.setText("")
        self.help_43.setPixmap(QtGui.QPixmap("C:/Users/slave/Desktop/help.png"))
        self.help_43.setScaledContents(True)
        self.help_43.setObjectName("help_43")
        self.gridLayout_10.addWidget(self.help_43, 4, 2, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.group_12)
        self.label_30.setAlignment(QtCore.Qt.AlignCenter)
        self.label_30.setObjectName("label_30")
        self.gridLayout_10.addWidget(self.label_30, 0, 0, 1, 1)
        self.label_92 = QtWidgets.QLabel(self.group_12)
        self.label_92.setAlignment(QtCore.Qt.AlignCenter)
        self.label_92.setObjectName("label_92")
        self.gridLayout_10.addWidget(self.label_92, 3, 0, 1, 1)
        self.input_55 = QtWidgets.QLineEdit(self.group_12)
        self.input_55.setObjectName("input_55")
        self.gridLayout_10.addWidget(self.input_55, 2, 1, 1, 1)
        self.input_58 = QtWidgets.QLineEdit(self.group_12)
        self.input_58.setObjectName("input_58")
        self.gridLayout_10.addWidget(self.input_58, 5, 1, 1, 1)
        self.input_59 = QtWidgets.QLineEdit(self.group_12)
        self.input_59.setObjectName("input_59")
        self.gridLayout_10.addWidget(self.input_59, 6, 1, 1, 1)
        self.help_41 = QtWidgets.QLabel(self.group_12)
        self.help_41.setMaximumSize(QtCore.QSize(20, 20))
        self.help_41.setText("")
        self.help_41.setPixmap(QtGui.QPixmap("C:/Users/slave/Desktop/help.png"))
        self.help_41.setScaledContents(True)
        self.help_41.setObjectName("help_41")
        self.gridLayout_10.addWidget(self.help_41, 2, 2, 1, 1)
        self.help_40 = QtWidgets.QLabel(self.group_12)
        self.help_40.setMaximumSize(QtCore.QSize(20, 20))
        self.help_40.setText("")
        self.help_40.setPixmap(QtGui.QPixmap("C:/Users/slave/Desktop/help.png"))
        self.help_40.setScaledContents(True)
        self.help_40.setObjectName("help_40")
        self.gridLayout_10.addWidget(self.help_40, 1, 2, 1, 1)
        self.label_39 = QtWidgets.QLabel(self.group_12)
        self.label_39.setAlignment(QtCore.Qt.AlignCenter)
        self.label_39.setObjectName("label_39")
        self.gridLayout_10.addWidget(self.label_39, 2, 0, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.group_12)
        self.label_37.setAlignment(QtCore.Qt.AlignCenter)
        self.label_37.setObjectName("label_37")
        self.gridLayout_10.addWidget(self.label_37, 1, 0, 1, 1)
        self.input_56 = QtWidgets.QLineEdit(self.group_12)
        self.input_56.setObjectName("input_56")
        self.gridLayout_10.addWidget(self.input_56, 3, 1, 1, 1)
        self.help_39 = QtWidgets.QLabel(self.group_12)
        self.help_39.setMaximumSize(QtCore.QSize(20, 20))
        self.help_39.setText("")
        self.help_39.setPixmap(QtGui.QPixmap("C:/Users/slave/Desktop/help.png"))
        self.help_39.setScaledContents(True)
        self.help_39.setObjectName("help_39")
        self.gridLayout_10.addWidget(self.help_39, 0, 2, 1, 1)
        self.input_53 = QtWidgets.QLineEdit(self.group_12)
        self.input_53.setObjectName("input_53")
        self.gridLayout_10.addWidget(self.input_53, 0, 1, 1, 1)
        self.label_94 = QtWidgets.QLabel(self.group_12)
        self.label_94.setAlignment(QtCore.Qt.AlignCenter)
        self.label_94.setObjectName("label_94")
        self.gridLayout_10.addWidget(self.label_94, 6, 0, 1, 1)
        self.help_42 = QtWidgets.QLabel(self.group_12)
        self.help_42.setMaximumSize(QtCore.QSize(20, 20))
        self.help_42.setText("")
        self.help_42.setPixmap(QtGui.QPixmap("C:/Users/slave/Desktop/help.png"))
        self.help_42.setScaledContents(True)
        self.help_42.setObjectName("help_42")
        self.gridLayout_10.addWidget(self.help_42, 3, 2, 1, 1)
        self.help_44 = QtWidgets.QLabel(self.group_12)
        self.help_44.setMaximumSize(QtCore.QSize(20, 20))
        self.help_44.setText("")
        self.help_44.setPixmap(QtGui.QPixmap("C:/Users/slave/Desktop/help.png"))
        self.help_44.setScaledContents(True)
        self.help_44.setObjectName("help_44")
        self.gridLayout_10.addWidget(self.help_44, 5, 2, 1, 1)
        self.help_45 = QtWidgets.QLabel(self.group_12)
        self.help_45.setMaximumSize(QtCore.QSize(20, 20))
        self.help_45.setText("")
        self.help_45.setPixmap(QtGui.QPixmap("C:/Users/slave/Desktop/help.png"))
        self.help_45.setScaledContents(True)
        self.help_45.setObjectName("help_45")
        self.gridLayout_10.addWidget(self.help_45, 6, 2, 1, 1)
        self.gridLayout_10.setColumnStretch(0, 1)
        self.gridLayout_10.setColumnStretch(1, 3)
        self.gridLayout_10.setColumnStretch(2, 1)
        self.horizontalLayout_5.addLayout(self.gridLayout_10)
        self.verticalLayout_6.addWidget(self.group_12)
        self.verticalLayout_6.setStretch(0, 1)
        self.verticalLayout_6.setStretch(1, 4)
        self.verticalLayout_6.setStretch(2, 7)
        self.tabWidget.addTab(self.tabStep_4, "")
        self.tabStep_5 = QtWidgets.QWidget()
        self.tabStep_5.setObjectName("tabStep_5")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.tabStep_5)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.group_13 = QtWidgets.QGroupBox(self.tabStep_5)
        self.group_13.setObjectName("group_13")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.group_13)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.gridLayout_13 = QtWidgets.QGridLayout()
        self.gridLayout_13.setContentsMargins(10, 10, 50, 10)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.input_66 = QtWidgets.QComboBox(self.group_13)
        self.input_66.setObjectName("input_66")
        self.input_66.addItem("")
        self.input_66.addItem("")
        self.gridLayout_13.addWidget(self.input_66, 6, 1, 1, 1)
        self.input_67 = QtWidgets.QComboBox(self.group_13)
        self.input_67.setObjectName("input_67")
        self.input_67.addItem("")
        self.input_67.addItem("")
        self.gridLayout_13.addWidget(self.input_67, 7, 1, 1, 1)
        self.input_62 = QtWidgets.QComboBox(self.group_13)
        self.input_62.setObjectName("input_62")
        self.input_62.addItem("")
        self.input_62.addItem("")
        self.gridLayout_13.addWidget(self.input_62, 2, 1, 1, 1)
        self.input_61 = QtWidgets.QComboBox(self.group_13)
        self.input_61.setObjectName("input_61")
        self.input_61.addItem("")
        self.input_61.addItem("")
        self.gridLayout_13.addWidget(self.input_61, 1, 1, 1, 1)
        self.label_104 = QtWidgets.QLabel(self.group_13)
        self.label_104.setAlignment(QtCore.Qt.AlignCenter)
        self.label_104.setObjectName("label_104")
        self.gridLayout_13.addWidget(self.label_104, 7, 0, 1, 1)
        self.input_63 = QtWidgets.QComboBox(self.group_13)
        self.input_63.setObjectName("input_63")
        self.input_63.addItem("")
        self.input_63.addItem("")
        self.gridLayout_13.addWidget(self.input_63, 3, 1, 1, 1)
        self.input_65 = QtWidgets.QComboBox(self.group_13)
        self.input_65.setObjectName("input_65")
        self.input_65.addItem("")
        self.input_65.addItem("")
        self.gridLayout_13.addWidget(self.input_65, 5, 1, 1, 1)
        self.input_64 = QtWidgets.QComboBox(self.group_13)
        self.input_64.setObjectName("input_64")
        self.input_64.addItem("")
        self.input_64.addItem("")
        self.gridLayout_13.addWidget(self.input_64, 4, 1, 1, 1)
        self.label_105 = QtWidgets.QLabel(self.group_13)
        self.label_105.setAlignment(QtCore.Qt.AlignCenter)
        self.label_105.setObjectName("label_105")
        self.gridLayout_13.addWidget(self.label_105, 8, 0, 1, 1)
        self.label_97 = QtWidgets.QLabel(self.group_13)
        self.label_97.setAlignment(QtCore.Qt.AlignCenter)
        self.label_97.setObjectName("label_97")
        self.gridLayout_13.addWidget(self.label_97, 0, 0, 1, 1)
        self.label_102 = QtWidgets.QLabel(self.group_13)
        self.label_102.setAlignment(QtCore.Qt.AlignCenter)
        self.label_102.setObjectName("label_102")
        self.gridLayout_13.addWidget(self.label_102, 5, 0, 1, 1)
        self.label_99 = QtWidgets.QLabel(self.group_13)
        self.label_99.setAlignment(QtCore.Qt.AlignCenter)
        self.label_99.setObjectName("label_99")
        self.gridLayout_13.addWidget(self.label_99, 2, 0, 1, 1)
        self.label_100 = QtWidgets.QLabel(self.group_13)
        self.label_100.setAlignment(QtCore.Qt.AlignCenter)
        self.label_100.setObjectName("label_100")
        self.gridLayout_13.addWidget(self.label_100, 3, 0, 1, 1)
        self.label_98 = QtWidgets.QLabel(self.group_13)
        self.label_98.setAlignment(QtCore.Qt.AlignCenter)
        self.label_98.setObjectName("label_98")
        self.gridLayout_13.addWidget(self.label_98, 1, 0, 1, 1)
        self.label_103 = QtWidgets.QLabel(self.group_13)
        self.label_103.setAlignment(QtCore.Qt.AlignCenter)
        self.label_103.setObjectName("label_103")
        self.gridLayout_13.addWidget(self.label_103, 6, 0, 1, 1)
        self.label_101 = QtWidgets.QLabel(self.group_13)
        self.label_101.setAlignment(QtCore.Qt.AlignCenter)
        self.label_101.setObjectName("label_101")
        self.gridLayout_13.addWidget(self.label_101, 4, 0, 1, 1)
        self.input_60 = QtWidgets.QComboBox(self.group_13)
        self.input_60.setObjectName("input_60")
        self.input_60.addItem("")
        self.input_60.addItem("")
        self.gridLayout_13.addWidget(self.input_60, 0, 1, 1, 1)
        self.input_68 = QtWidgets.QComboBox(self.group_13)
        self.input_68.setObjectName("input_68")
        self.input_68.addItem("")
        self.input_68.addItem("")
        self.gridLayout_13.addWidget(self.input_68, 8, 1, 1, 1)
        self.help_46 = QtWidgets.QLabel(self.group_13)
        self.help_46.setMaximumSize(QtCore.QSize(20, 20))
        self.help_46.setText("")
        self.help_46.setPixmap(QtGui.QPixmap("C:/Users/slave/Desktop/help.png"))
        self.help_46.setScaledContents(True)
        self.help_46.setObjectName("help_46")
        self.gridLayout_13.addWidget(self.help_46, 0, 2, 1, 1)
        self.help_47 = QtWidgets.QLabel(self.group_13)
        self.help_47.setMaximumSize(QtCore.QSize(20, 20))
        self.help_47.setText("")
        self.help_47.setPixmap(QtGui.QPixmap("C:/Users/slave/Desktop/help.png"))
        self.help_47.setScaledContents(True)
        self.help_47.setObjectName("help_47")
        self.gridLayout_13.addWidget(self.help_47, 1, 2, 1, 1)
        self.help_48 = QtWidgets.QLabel(self.group_13)
        self.help_48.setMaximumSize(QtCore.QSize(20, 20))
        self.help_48.setText("")
        self.help_48.setPixmap(QtGui.QPixmap("C:/Users/slave/Desktop/help.png"))
        self.help_48.setScaledContents(True)
        self.help_48.setObjectName("help_48")
        self.gridLayout_13.addWidget(self.help_48, 2, 2, 1, 1)
        self.help_49 = QtWidgets.QLabel(self.group_13)
        self.help_49.setMaximumSize(QtCore.QSize(20, 20))
        self.help_49.setText("")
        self.help_49.setPixmap(QtGui.QPixmap("C:/Users/slave/Desktop/help.png"))
        self.help_49.setScaledContents(True)
        self.help_49.setObjectName("help_49")
        self.gridLayout_13.addWidget(self.help_49, 3, 2, 1, 1)
        self.help_50 = QtWidgets.QLabel(self.group_13)
        self.help_50.setMaximumSize(QtCore.QSize(20, 20))
        self.help_50.setText("")
        self.help_50.setPixmap(QtGui.QPixmap("C:/Users/slave/Desktop/help.png"))
        self.help_50.setScaledContents(True)
        self.help_50.setObjectName("help_50")
        self.gridLayout_13.addWidget(self.help_50, 4, 2, 1, 1)
        self.help_51 = QtWidgets.QLabel(self.group_13)
        self.help_51.setMaximumSize(QtCore.QSize(20, 20))
        self.help_51.setText("")
        self.help_51.setPixmap(QtGui.QPixmap("C:/Users/slave/Desktop/help.png"))
        self.help_51.setScaledContents(True)
        self.help_51.setObjectName("help_51")
        self.gridLayout_13.addWidget(self.help_51, 5, 2, 1, 1)
        self.help_52 = QtWidgets.QLabel(self.group_13)
        self.help_52.setMaximumSize(QtCore.QSize(20, 20))
        self.help_52.setText("")
        self.help_52.setPixmap(QtGui.QPixmap("C:/Users/slave/Desktop/help.png"))
        self.help_52.setScaledContents(True)
        self.help_52.setObjectName("help_52")
        self.gridLayout_13.addWidget(self.help_52, 6, 2, 1, 1)
        self.help_53 = QtWidgets.QLabel(self.group_13)
        self.help_53.setMaximumSize(QtCore.QSize(20, 20))
        self.help_53.setText("")
        self.help_53.setPixmap(QtGui.QPixmap("C:/Users/slave/Desktop/help.png"))
        self.help_53.setScaledContents(True)
        self.help_53.setObjectName("help_53")
        self.gridLayout_13.addWidget(self.help_53, 7, 2, 1, 1)
        self.help_54 = QtWidgets.QLabel(self.group_13)
        self.help_54.setMaximumSize(QtCore.QSize(20, 20))
        self.help_54.setText("")
        self.help_54.setPixmap(QtGui.QPixmap("C:/Users/slave/Desktop/help.png"))
        self.help_54.setScaledContents(True)
        self.help_54.setObjectName("help_54")
        self.gridLayout_13.addWidget(self.help_54, 8, 2, 1, 1)
        self.horizontalLayout_11.addLayout(self.gridLayout_13)
        self.verticalLayout_9.addWidget(self.group_13)
        self.tabWidget.addTab(self.tabStep_5, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton_2 = QtWidgets.QPushButton(mainWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton = QtWidgets.QPushButton(mainWidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.horizontalLayout.setStretch(0, 4)
        self.horizontalLayout.setStretch(1, 1)
        self.horizontalLayout.setStretch(2, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(mainWidget)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(mainWidget)

    def retranslateUi(self, mainWidget):
        _translate = QtCore.QCoreApplication.translate
        mainWidget.setWindowTitle(_translate("mainWidget", "追溯分析系统部署工具"))
        self.group_1.setTitle(_translate("mainWidget", "业务库"))
        self.label_76.setText(_translate("mainWidget", "账号"))
        self.label_77.setText(_translate("mainWidget", "数据库"))
        self.label_72.setText(_translate("mainWidget", "端口"))
        self.label_73.setText(_translate("mainWidget", "密码"))
        self.label_78.setText(_translate("mainWidget", "地址"))
        self.input_1.setText(_translate("mainWidget", "192.168.227.139"))
        self.input_5.setItemText(0, _translate("mainWidget", "请选择业务库"))
        self.input_2.setText(_translate("mainWidget", "1433"))
        self.getDBBtn_1.setText(_translate("mainWidget", "测试"))
        self.group_2.setTitle(_translate("mainWidget", "历史库"))
        self.label_85.setText(_translate("mainWidget", "数据库"))
        self.input_7.setText(_translate("mainWidget", "192.168.227.139"))
        self.label_81.setText(_translate("mainWidget", "密码"))
        self.label_86.setText(_translate("mainWidget", "地址"))
        self.input_8.setText(_translate("mainWidget", "1433"))
        self.label_84.setText(_translate("mainWidget", "账号"))
        self.label_80.setText(_translate("mainWidget", "端口"))
        self.input_6.setText(_translate("mainWidget", "是否抽取历史库"))
        self.input_11.setItemText(0, _translate("mainWidget", "请选择历史库"))
        self.getDBBtn_2.setText(_translate("mainWidget", "测试"))
        self.group_8.setTitle(_translate("mainWidget", "BI库"))
        self.input_13.setText(_translate("mainWidget", "1433"))
        self.label_116.setText(_translate("mainWidget", "密码"))
        self.label_117.setText(_translate("mainWidget", "端口"))
        self.input_12.setText(_translate("mainWidget", "192.168.227.139"))
        self.label_120.setText(_translate("mainWidget", "账号"))
        self.label_121.setText(_translate("mainWidget", "数据库"))
        self.label_122.setText(_translate("mainWidget", "地址"))
        self.label_123.setText(_translate("mainWidget", "数据源编号"))
        self.label_124.setText(_translate("mainWidget", "数据源名称"))
        self.group_3.setTitle(_translate("mainWidget", "系统库"))
        self.label_64.setText(_translate("mainWidget", "端口"))
        self.label_65.setText(_translate("mainWidget", "密码"))
        self.input_19.setText(_translate("mainWidget", "192.168.227.139"))
        self.label_68.setText(_translate("mainWidget", "账号"))
        self.label_69.setText(_translate("mainWidget", "数据库"))
        self.label_70.setText(_translate("mainWidget", "地址"))
        self.input_20.setText(_translate("mainWidget", "1433"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabStep_1), _translate("mainWidget", "Step1.数据库"))
        self.group_14.setTitle(_translate("mainWidget", "工艺参数"))
        self.label_126.setText(_translate("mainWidget", "密码"))
        self.label_38.setText(_translate("mainWidget", "账号"))
        self.label_41.setText(_translate("mainWidget", "映射目录"))
        self.label_43.setText(_translate("mainWidget", "映射地址"))
        self.input_24.setText(_translate("mainWidget", "是否启用工艺参数"))
        self.group_5.setTitle(_translate("mainWidget", "工艺参数库"))
        self.label_55.setText(_translate("mainWidget", "文件路径"))
        self.label_51.setText(_translate("mainWidget", "账号"))
        self.label_48.setText(_translate("mainWidget", "密码"))
        self.label_47.setText(_translate("mainWidget", "端口"))
        self.label_53.setText(_translate("mainWidget", "地址"))
        self.input_30.setText(_translate("mainWidget", "1433"))
        self.label_52.setText(_translate("mainWidget", "数据库"))
        self.input_29.setText(_translate("mainWidget", "192.168.227.139"))
        self.label_56.setText(_translate("mainWidget", "开始年月"))
        self.label_57.setText(_translate("mainWidget", "初始值(MB)"))
        self.label_58.setText(_translate("mainWidget", "结束年月"))
        self.label_59.setText(_translate("mainWidget", "增长值(MB)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabStep_2), _translate("mainWidget", "Step2.工艺参数"))
        self.group_6.setTitle(_translate("mainWidget", "基础配置"))
        self.label_15.setText(_translate("mainWidget", "系统版本"))
        self.label_18.setText(_translate("mainWidget", "业务端服务地址"))
        self.label_16.setText(_translate("mainWidget", "业务端服务端口"))
        self.group_7.setTitle(_translate("mainWidget", "部署程序"))
        self.label_3.setText(_translate("mainWidget", "网络共享地址"))
        self.label_5.setText(_translate("mainWidget", "共享密码"))
        self.label_4.setText(_translate("mainWidget", "共享账号"))
        self.group8.setTitle(_translate("mainWidget", "部署地址"))
        self.label_9.setText(_translate("mainWidget", "拷贝目录"))
        self.label_10.setText(_translate("mainWidget", "PowerShell目录"))
        self.label_12.setText(_translate("mainWidget", "安装目录"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabStep_3), _translate("mainWidget", "Step3.部署配置"))
        self.group_9.setTitle(_translate("mainWidget", "基础配置"))
        self.label_95.setText(_translate("mainWidget", "服务端口"))
        self.group_11.setTitle(_translate("mainWidget", "单点登录"))
        self.label_29.setText(_translate("mainWidget", "服务地址(MI)"))
        self.label_31.setText(_translate("mainWidget", "页面端口"))
        self.label_32.setText(_translate("mainWidget", "接口端口"))
        self.input_49.setText(_translate("mainWidget", "是否启用单点登录"))
        self.group_12.setTitle(_translate("mainWidget", "ETL配置"))
        self.label_93.setText(_translate("mainWidget", "账号"))
        self.input_57.setText(_translate("mainWidget", "是否启用登录"))
        self.label_30.setText(_translate("mainWidget", "工艺参数抽取目录"))
        self.label_92.setText(_translate("mainWidget", "抽取抽取频率(分钟)"))
        self.label_39.setText(_translate("mainWidget", "JVM(MB)"))
        self.label_37.setText(_translate("mainWidget", "ETL端口"))
        self.label_94.setText(_translate("mainWidget", "密码"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabStep_4), _translate("mainWidget", "Step4.系统配置"))
        self.group_13.setTitle(_translate("mainWidget", "定制配置"))
        self.input_66.setItemText(0, _translate("mainWidget", "停用"))
        self.input_66.setItemText(1, _translate("mainWidget", "启用"))
        self.input_67.setItemText(0, _translate("mainWidget", "停用"))
        self.input_67.setItemText(1, _translate("mainWidget", "启用"))
        self.input_62.setItemText(0, _translate("mainWidget", "停用"))
        self.input_62.setItemText(1, _translate("mainWidget", "启用"))
        self.input_61.setItemText(0, _translate("mainWidget", "停用"))
        self.input_61.setItemText(1, _translate("mainWidget", "启用"))
        self.label_104.setText(_translate("mainWidget", "断链"))
        self.input_63.setItemText(0, _translate("mainWidget", "停用"))
        self.input_63.setItemText(1, _translate("mainWidget", "启用"))
        self.input_65.setItemText(0, _translate("mainWidget", "停用"))
        self.input_65.setItemText(1, _translate("mainWidget", "启用"))
        self.input_64.setItemText(0, _translate("mainWidget", "停用"))
        self.input_64.setItemText(1, _translate("mainWidget", "启用"))
        self.label_105.setText(_translate("mainWidget", "过滤万能工单"))
        self.label_97.setText(_translate("mainWidget", "重构版本"))
        self.label_102.setText(_translate("mainWidget", "FGB"))
        self.label_99.setText(_translate("mainWidget", "设备维护"))
        self.label_100.setText(_translate("mainWidget", "工具管理"))
        self.label_98.setText(_translate("mainWidget", "遏制"))
        self.label_103.setText(_translate("mainWidget", "视频监控"))
        self.label_101.setText(_translate("mainWidget", "工艺参数"))
        self.input_60.setItemText(0, _translate("mainWidget", "重构后"))
        self.input_60.setItemText(1, _translate("mainWidget", "重构前"))
        self.input_68.setItemText(0, _translate("mainWidget", "过滤"))
        self.input_68.setItemText(1, _translate("mainWidget", "不过滤"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabStep_5), _translate("mainWidget", "Step5.工厂定制"))
        self.pushButton_2.setText(_translate("mainWidget", "Next"))
        self.pushButton.setText(_translate("mainWidget", "Cancel"))

